quattor/configuration-modules-core

ncm-nss/src/main/perl/nss.pm

A user complained they could not get the output of the buildDB command
unless it exited non-zero, even when running under debug mode.
Always log the command output as debug.
THE FOLLOWING DISCLAIMER APPLIES TO ALL SOFTWARE CODE AND OTHER MATERIALS
CONTRIBUTED IN CONNECTION WITH THIS PROGRAM.
THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE
DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
OF SUBSTITUTE GOODS OR SERVICES; …

ncm-nss: Log output of buildDB script as debug

---

ncm-cron/src/main/perl/cron.pod

Schema specifies long, but documented example shows a string.

Correct example smear from string to long

---

ncm-network/src/main/perl/network.pod

The last commit is most relevant, this fixes the example to use ```bonding_opts``` instead of modules which does not work anymore.
The rest is a cleanup of this pod:
- fixed pod errors
- style adjustments for escaping special chars etc.
- code blocks for examples instead of text
- ...

ncm-network: fix documentation bonding example

---

ncm-network/src/main/pan/components/network/core-schema.pan

When bonding with LACP is configured (mode=4), updelay and primary are not required but lacp_rate is.

ncm-network: allow for bonding with lacp while keeping validation

---

ncm-sudo/src/main/pan/components/sudo/schema.pan

For example, it may be possible to only set include_dirs and defining all privilege_lines in files in this include_dirs.

ncm-sudo: the privilege_lines option should be optional.

---

ncm-icinga/src/main/pan/components/icinga/schema.pan

They can also be defined in the contact group definition. Both are valid.

ncm-icinga: contact group definition is not mandatory for contacts. 

---

ncm-network/src/main/pan/components/network/core-schema.pan

This allows changing the default hash policy for outgoing traffic slave selection.

ncm-network: add xmit_hash_policy as an allowed bonding option

---

ncm-cron/src/main/perl/cron.pm
ncm-cron/src/main/perl/cron.pod

There is a race condition: when the component mass creates files (within a second) cron may read in just some of the cronjobs ignoring all the others until crond restarted or the host is rebooted. RedHat 5 has this bug.
RH6 uses inotify and not suspectible to this.
By touching /etc/cron.d we force crond to re-read all the files (cronjobs).

ncm-cron: Fix race condition bug

---

ncm-modprobe/src/main/pan/components/modprobe/schema.pan
ncm-modprobe/src/main/perl/modprobe.pm
ncm-modprobe/src/main/perl/modprobe.pod
ncm-modprobe/src/test/perl/generator.t
ncm-modprobe/src/test/perl/process_aliases.t
ncm-modprobe/src/test/perl/process_blacklist.t
ncm-modprobe/src/test/perl/process_install.t

This should fix bugs #412 and #413 and add "blacklist" functionality.

ncm-modprobe: fix for install, remove and options, added blacklist

---

ncm-sudo/src/main/perl/sudo.pm
ncm-sudo/src/test/perl/options.t
ncm-sudo/src/test/perl/sudoers.t
ncm-sudo/src/test/resources/profile_all_options.pan

Specifying multiple options was possible, but untested by the unit tests, the delimiter was incorrectly specified as a tab character rather than a comma.
Fixes #460 as reported by @drossy.

ncm-sudo: Fix generation of parameter lists

---

ncm-authconfig/src/main/pan/components/authconfig/schema.pan

The sssd-ldap man page appears to be incorrect, the autofs schema e.g. http://people.redhat.com/nalin/schema/autofs.schema actually uses automount for the map entries not automountMap

ncm-authconfig: Correct ldap object class for automount entries

---

ncm-autofs/src/main/perl/autofs.pm

Slight modification to add the direct mount support.
Fixes #335 
This fix works with the following pan example:
```
include {'features/nfs/client/autofs'};
include {'components/autofs/config'};
variable USER_ENTRIES = {
tbl = nlist(escape("/MY_MOUNTPOINT"),nlist("location","MY_SERVER:/MY_EXPORT","options",""));
};
"/software/components/autofs/maps/MY_MOUNTPOINT" = nlist(
"enabled",true,
"mapname","/etc/auto.direct",
"mountpoint","/-",
"options","-rw",
"type","direct",
"entries", USER_ENTRIES
);
```
Credit @StephaneGerardVUB

ncm-autofs: Add direct mount support

---

ncm-ceph/src/main/perl/Ceph/commands.pm

`test_host_connection` is trying to access the `homeDir` variable under `$gvalues` when it's under `$gvalues->{cephusr}`.

ncm-ceph: fix test_host_connection tries to access homeDir from wrong place

---

ncm-ceph/src/main/pan/components/ceph/schema.pan

The original implementation of the `straw` algorithm is flawed as Sage Weil describes [here](http://comments.gmane.org/gmane.comp.file-systems.ceph.devel/22317)
With the release of Hammer, `straw2` is now available which fixes what was wrong with the old algorithm.
There is no reason for any new Ceph cluster running Hammer to use straw.
Ideally, straw2 would be automatically chosen as the default algorithm for a cluster running Hammer or later.

ncm-ceph: Add `straw2` as possible bucket algorithm

---

ncm-mysql/src/main/perl/mysql.pm

Fixes #480.
Not tested on real systems.

ncm-mysql: Flush privileges after user and database operations

---

ncm-metaconfig/src/main/metaconfig/ganesha/pan/schema.pan

The Access attribute is assumed a comma separated list in the TT files (and auto-promotion from scalar to list with the CCM::TT::Scalar instances seems to fail with TT on EL5)
Fixes #499

ncm-metaconfig: service ganesha service change stat_exporter Access type

---

ncm-mysql/src/main/pan/components/mysql/schema.pan

Required for backward compatibily. If desirable to change this, it would be good to open a separate issue and discuss it as part of 15.6 release.
Also applies the same validation rules for admin password (empty password excluded)
Fixes #506

ncm-mysql: allow an empty password for a DB user

---

ncm-spma/src/main/pan/components/spma/repository_cleanup.pan

- useless with YUM-based AII
Fixes a potential issue idendified during 15.4.0-rc4 (https://github.com/quattor/release/issues/96).

ncm-spma: remove call to resolve_pkg_rep

---

ncm-metaconfig/src/main/metaconfig/rpcidmapd/pan/config.pan

Service rpcidmap: support different name for daemon to restart via prefix as precise name depends on OS version.

ncm-metaconfig: service rpcidmap: control service name via RPCIDMAPD_SERVICE_PREFIX

---

ncm-metaconfig/src/main/metaconfig/logstash/1.2/tests/profiles/forwarder.pan
ncm-metaconfig/src/main/metaconfig/logstash/1.2/tests/regexps/forwarder/base
ncm-metaconfig/src/main/metaconfig/logstash/pan/forwarder.pan

With the first 0.4.0 rpm released by elastic, the default configfile used by the rpm is now in `/etc/logstash-forwarder.conf`

ncm-metaconfig: service logstash: change forwarder configfile location 

---

ncm-sudo/src/main/pan/components/sudo/schema.pan
ncm-sudo/src/main/perl/sudo.pm

Hi,
One change is for ncm-sudo on Solaris, it fails because /proc/self/fd/0 is not a valid handle for stdin. Use a - instead on Solaris (this doesn't seem to work on a Linux tested).
Also, while trying to upgrade to the latest upstream, we are having a problem with the schema change in e79f799. The privilege options parameter was changed to require a colon at the end, which we do not have in our templates. It is difficult because it requires that we change the schema, templates and components all at once. So I propose this change which, I hope, will allow them to be changed independently. It does this by making the colon optional in the schema, and adding it in the code if it's not present.
Finally, a true (1) return was missing at the end of the package.

ncm-sudo fixes

---

ncm-ceph/src/main/perl/ceph.pm

Small fix. Otherwise will give error on non-deploy host where ceph-deploy is not installed (eg. when using localdaemons structure to configure ceph)

ncm-ceph: Only check ceph-deploy version on deployhost

---

ncm-metaconfig/src/main/metaconfig/logstash/1.2/filter/bytes2human.tt
ncm-metaconfig/src/main/metaconfig/logstash/1.2/filter/kv.tt
ncm-metaconfig/src/main/metaconfig/logstash/1.2/filter/plugin.tt
ncm-metaconfig/src/main/metaconfig/logstash/1.2/tests/profiles/server.pan
ncm-metaconfig/src/main/metaconfig/logstash/1.2/tests/regexps/server/base
ncm-metaconfig/src/main/metaconfig/logstash/pan/schema.pan

Add support for the `bytes2human` and `kv` filters.

ncm-metaconfig: service logstash add support for filter kv

---

ncm-metaconfig/src/main/metaconfig/named/named.tt
ncm-metaconfig/src/main/metaconfig/named/tests/profiles/config.pan
ncm-metaconfig/src/main/metaconfig/named/tests/regexps/config/base

Although multiple includes separated by `;` is valid, inserting a newline after each include makes it much more readable

ncm-metaconfig: named: add newline after each include

---

ncm-download/src/main/pan/components/download/schema.pan
ncm-download/src/main/perl/download.pm

We've been having problems with the ncm-download component taking a long time to timeout because there is no timeout set.
I found some code in sudo.pm which adds a timeout switch to the curl command (though it is not in the schema). However, there is no timeout on the LWP client which does the HEAD request before this.
So I've added a head_timeout parameter at the component level, with a default of 3 seconds set. The curl timeout has been added to schema.pan, and it is possible to override it per file.

ncm-download timeouts

---

ncm-opennebula/src/main/pan/components/opennebula/schema.pan

This PR includes a small schema fix to check opennebula db backend.
https://github.com/quattor/template-library-core/issues/69 : schema should allow for the possibility to use sqlite as one db backend

ncm-opennebula: Fix database schema

---

ncm-ceph/src/main/pan/components/ceph/schema.pan
ncm-ceph/src/main/perl/Ceph/commands.pm
ncm-ceph/src/main/perl/Ceph/compare.pm
ncm-ceph/src/main/perl/Ceph/config.pm
ncm-ceph/src/main/perl/Ceph/crushmap.pm
ncm-ceph/src/main/perl/Ceph/daemon.pm
ncm-ceph/src/main/perl/ceph.pm
ncm-ceph/src/test/perl/30-compare1.t
ncm-ceph/src/test/perl/32-compare2.t
ncm-ceph/src/test/perl/53-crushmap-label.t
ncm-ceph/src/test/perl/crushdata.pm
ncm-ceph/src/test/perl/data.pm
ncm-ceph/src/test/resources/basic_cluster.pan
ncm-ceph/src/test/resources/labeled_crushmap.pan

- add `max_add_osd_failures_per_host` option to be flexible with osd failures
- change schema to be able to use per host osd templates that are included on the deployhost.
- change injection to a warning: injecting on a host base does not work (anymore)
- remove empty crushmap buckets when labeling

ncm-ceph: various additions

---

ncm-network/src/main/pan/components/network/core-schema.pan

This is inserted by aquilon for any aliases with hostnames.

ncm-network: Add fqdn to interface_alias type

---

ncm-network/src/main/perl/network.pm

As documented at:
* http://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/
* https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Networking_Guide/ch-Consistent_Network_Device_Naming.html
* http://cgit.freedesktop.org/systemd/systemd/tree/src/udev/udev-builtin-net_id.c#n20

ncm-network: Support all five systemd device naming schemes

---

ncm-authconfig/src/main/pan/components/authconfig/schema.pan
ncm-authconfig/src/main/perl/authconfig.pm
ncm-authconfig/src/test/perl/update_pam.t
ncm-authconfig/src/test/resources/pamadditions.pan

ncm-authconfig: correct module regexp for pamadditions entry attribute

---

ncm-ccm/src/main/pan/components/ccm/schema.pan
ncm-ccm/src/main/perl/ccm.pm

CCM will be supporting multiple failover URLs (comma seperated in the
config file) so this change will allow that to be configured by this
component. Code is backwards compatible with old schema.

ncm-ccm: change profile_failover from hostURI to hostURI[].

---

ncm-icinga/src/main/pan/components/icinga/schema.pan
ncm-nagios/src/main/pan/components/nagios/schema.pan

Removes duplicate type definitions which allows both components to be included
which gets us one step closer to having unit tests pass on template-library-core.

ncm-nagios & ncm-icinga: Seperate type definitions

---

ncm-spma/src/main/pan/components/spma/functions.pan

Needed to get unit-tests passing on `template-library-core`

ncm-spma: purge_rep_list - Do nothing if SELF is not defined

---

ncm-ccm/src/main/pan/components/ccm/config.pan
ncm-ccm/src/main/pan/components/ccm/schema.pan
ncm-ccm/src/test/resources/base.pan

Allows ncm-ccm to enable tabcompletion generation, which is disabled by default in CCM

ncm-ccm: add tabcompletion option

---

ncm-modprobe/src/test/perl/process_aliases.t
ncm-modprobe/src/test/perl/process_blacklist.t
ncm-modprobe/src/test/perl/process_install.t

Avoids DESTROY issue (see #432)

ncm-modprobe: close the mocked filehandles in the test 

---

ncm-ccm/src/main/perl/ccm.pm

ccm-fetch should be used with --cfgfile instead of -cfgfile, as advertised by CAF::Application (although -cfgfile should work for Appconfig)
partially fixes https://github.com/quattor/release/issues/109#issuecomment-144091675

ncm-ccm: use --cfgfile instead of -cfgfile to test new config file

---

ncm-ccm/src/main/perl/ccm.pm
ncm-ccm/src/test/perl/configure.t

ncm-ccm: do not use stdin for tetsing with ccm-fetch

---

ncm-network/src/main/pan/components/network/core-schema.pan

A valid NIS domain is (as far as anyone can tell) a string of up to sixty-four non-whitespace characters.
Fixes #604

ncm-network: change type of nisdomain to something closer to reality

---

ncm-ssh/src/main/pan/components/ssh/schema.pan
ncm-ssh/src/main/perl/ssh.pm
ncm-ssh/src/test/perl/valid.t

* Add GSSAPIKeyExchange, GSSAPIStrictAcceptorCheck,
KerberosTicketAuthentication back into schema.
* /dev/stdin because /proc/self does not exist on Solaris and
possibly other UNIX.
* Add support for multiline options back in, determined by
a list in the code.
* Don't hardcode the sshd/sshd_config/ssh_config (/usr/sbin/sshd
doesn't exist for us), make it possible to set through profile.
Backwards incompatible schema change - AcceptEnv, ListenAddress, HostKey changed to arrays.

ncm-ssh: fix some issues introduced during rewrite.

---

ncm-hostsfile/src/main/perl/hostsfile.pm

The logging declares its intent to remove some entries which were
previously managed by NCM, but then adds them into the file output
instead of skipping them.

ncm-hostsfile: fix removal of old entries which were managed by NCM.

---

ncm-download/src/main/perl/download.pm

to prevent failure to get timestamp if gssapi is required and enabled.

ncm-download: allow kinit to run in NoAction mode.

---

ncm-ssh/src/main/pan/components/ssh/schema.pan
ncm-ssh/src/main/perl/ssh.pm

small oversight on my part in the previous PR regarding this component during build time for us. sshd is on a network FS which isn't available at build time, so I've added a new param where you can make this check skip if sshd isn't existing.
existing behaviour, to always check, is still the default.

ncm-ssh: make config checks configurable.

---

ncm-metaconfig/src/main/pan/components/metaconfig/schema.pan

The daemon property was a good start, but is now deprecated and replaced with the daemons structure.
This removes the deprecated property, the code associated with it and anything that was testing it.
Fixes #431

ncm-metaconfig: remove daemon property

---

ncm-filecopy/src/main/pan/components/filecopy/schema.pan
ncm-metaconfig/src/main/pan/components/metaconfig/schema.pan

Checks for trailing slashes and throws a helpful error.
Fixes #627, requires quattor/template-library-core#96.

ncm-filecopy, ncm-metaconfig: validate file paths

---

ncm-ceph/src/main/perl/Ceph/commands.pm
ncm-ceph/src/main/perl/Ceph/compare.pm
ncm-ceph/src/main/perl/Ceph/daemon.pm
ncm-ceph/src/main/perl/ceph.pm
ncm-ceph/src/test/perl/06-ssh-keys.t
ncm-ceph/src/test/perl/20-config.t
ncm-ceph/src/test/perl/43-restart-dest.t
ncm-ceph/src/test/perl/data.pm
ncm-ceph/src/test/resources/regexps/destroyrestart

ncm-ceph: fix user for known_hosts and fix output for destroy and restart

---

ncm-network/src/main/perl/network.pm

* Fix #651 : ovs_extra is not set correctly

ncm-network: Fix ovs_extra network script output

---

ncm-metaconfig/src/main/metaconfig/logstash/1.2/tests/profiles/config.pan
ncm-metaconfig/src/main/metaconfig/logstash/1.2/tests/profiles/server.pan
ncm-metaconfig/src/main/metaconfig/logstash/1.2/tests/regexps/config/base
ncm-metaconfig/src/main/metaconfig/logstash/1.2/tests/regexps/server/base
ncm-metaconfig/src/main/metaconfig/logstash/2.0/tests/profiles/config.pan
ncm-metaconfig/src/main/metaconfig/logstash/2.0/tests/profiles/server.pan
ncm-metaconfig/src/main/metaconfig/logstash/2.0/tests/regexps/config/base
ncm-metaconfig/src/main/metaconfig/logstash/2.0/tests/regexps/server/base
ncm-metaconfig/src/main/metaconfig/logstash/config/types/name_pattern.tt
ncm-metaconfig/src/main/metaconfig/logstash/pan/schema.pan

The logstash grok filter supports a list of patterns  as value for each match.

ncm-metaconfig: service logstash: filter grok: the match pattern support a list of patterns

---

ncm-network/src/main/perl/network.pm

This is a normal situation, so treat them the same as other meta interfaces.
Fixes #609.

ncm-network: Don't warn if hwaddr is missing from bridge interfaces

---

ncm-systemd/src/main/perl/Systemd/Service/Unit.pm
ncm-systemd/src/main/perl/Systemd/Systemctl.pm
ncm-systemd/src/test/perl/service-unit.t

ncm-systemd: allow non-listed unit(file)s that have valid show data

---

ncm-symlink/src/main/perl/symlink.pm

This is a quick fix for a component that deserves a full rewrite (#683) using the `getTree()` API...

ncm-symlink: fix message for duplicated links

---

ncm-systemd/src/main/perl/Systemd/Service/Unit.pm
ncm-systemd/src/test/perl/service-unit.t

ncm-systemd: always use systemctl show data for non-listed unit

---

ncm-nfs/src/main/perl/nfs.pod

The schema and perl code indicate that hosts is a dict of host-option pairs, but the example in the pod shows a bogus list. Also tidy up the example code block while we are at it.
Spotted by @apdibbo.

ncm-nfs: fix incorrect exports hosts example in documentation 

---

ncm-metaconfig/src/main/metaconfig/logstash/2.0/tests/profiles/server.pan
ncm-metaconfig/src/main/metaconfig/logstash/config/filter/mutate.tt
ncm-metaconfig/src/main/metaconfig/logstash/pan/schema.pan

ncm-metaconfig: service logstash: use a sensible type for mutate convert

---

ncm-metaconfig/src/main/metaconfig/elasticsearch/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/elasticsearch/tests/profiles/config.pan

https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery-zen.html

ncm-metaconfig: service elasticsearch support discovery.zen

---

ncm-metaconfig/src/main/pan/components/metaconfig/config.pan

Not having the version published makes `metaconfig` usage complicated in templates that must still support Quattor 13.1. It'd be great to have it fixed in 15.12 but I don't dare to ask for it...!!!

ncm-metaconfig: publish component version

---

ncm-metaconfig/src/main/metaconfig/xinetd/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/xinetd/pan/services/time-stream.pan
ncm-metaconfig/src/main/metaconfig/xinetd/tests/profiles/time-stream.pan
ncm-metaconfig/src/main/metaconfig/xinetd/tests/regexps/time-stream/base

we used to enable time-stream through chkconfig. because of https://github.com/quattor/configuration-modules-core/issues/693 we now want it do it through metaconfig. So this adds support for time-stream.

ncm-metaconfig: add timestream basic config

---

ncm-aiiserver/src/main/perl/aiiserver.pod

Currently the `aii` links are dead ends and there is no correct link to point them at.
The following changes render them as code, rather than links. They can become links again, once they have have something to link to. 
Fixes quattor/quattor.github.com#128.

Change 'aii' links to render as code instead of links

---

ncm-metaconfig/src/main/metaconfig/logstash/2.0/tests/profiles/server.pan
ncm-metaconfig/src/main/metaconfig/logstash/2.0/tests/regexps/server/base
ncm-metaconfig/src/main/metaconfig/logstash/config/filter/mutate.tt
ncm-metaconfig/src/main/metaconfig/logstash/config/filter/plugin.tt
ncm-metaconfig/src/main/metaconfig/logstash/config/input/plugin.tt
ncm-metaconfig/src/main/metaconfig/logstash/config/output/plugin.tt
ncm-metaconfig/src/main/metaconfig/logstash/config/types/escstringhash.tt
ncm-metaconfig/src/main/metaconfig/logstash/pan/schema.pan

metaconfig: service logstash: support escaped add_field keys

---

ncm-metaconfig/src/main/metaconfig/httpd/pan/schema.pan

Add shibboleth as a supported value of httpd_auth_require.

ncm-metaconfig: httpd auth require add shibboleth

---

ncm-metaconfig/src/main/metaconfig/lmod/main.tt
ncm-metaconfig/src/main/metaconfig/lmod/pan/config.pan
ncm-metaconfig/src/main/metaconfig/lmod/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/lmod/prop.tt
ncm-metaconfig/src/main/metaconfig/lmod/scDescript.tt
ncm-metaconfig/src/main/metaconfig/lmod/tests/profiles/default.pan
ncm-metaconfig/src/main/metaconfig/lmod/tests/regexps/default/base
ncm-metaconfig/src/test/perl/service-lmod.t

New metaconfig service for site global configuration of [lmod](https://github.com/TACC/Lmod)

ncm-metaconfig: add service lmod

---

ncm-metaconfig/src/main/metaconfig/ncm-ncd/pan/config.pan

Don't try to restart ncm-ncd, it is not a demon, so there is no ncm-ncd service!

ncm-metaconfig: service ncm-ncd - do not try to restart daemons

---

ncm-ceph/src/main/pan/components/ceph/ceph-user.pan

Infernalis wants a specific uid for the ceph user. To be backwards compatible with running cluster, by default nothing changes, but a deprecated message is added. When installing new clusters, or going to infernalis, you should set CEPH_OLD_UID to false

ncm-ceph: ceph uid for infernalis

---

ncm-metaconfig/src/main/metaconfig/icinga-web/manager_attrs.tt

upper() is not available in earlier versions of template toolkit so this breaks pre SL7 support.

ncm-metaconfig: icinga-web - Use FILTER to convert to uppercase, not string method

---

ncm-ccm/src/main/pan/components/ccm/schema.pan

Using upper case characters for Kerberos realms is the convention, but
some organisations may be using lower case realms without issue.

ncm-ccm: allow lowercase characters in trust realm.

---

ncm-syslogng/src/main/perl/syslogng.pm

it passes $cfg->{flags} into print_log_flags, then checks this hash for flags too, so it always returns and never prints any flags.

ncm-syslogng: fix flags support.

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

The practices we have adopted for managing issues and pull-requests on GitHub have not been documented anywhere, this has the advantage of both documenting those practices and then directly exposing them to everyone.
See https://github.com/blog/2111-issue-and-pull-request-templates

Add templates for new issues and pull-requests

---

ncm-ssh/src/main/perl/ssh.pm

The escaping was for the regex passed into add_or_replace_lines, not the
sshd_config file itself. Multiline options don't use regex, so the
values should not have been escaped in the same way.

ncm-ssh: Fix for multiline option values with special chars.

---

ncm-metaconfig/src/main/metaconfig/keepalived/global.tt
ncm-metaconfig/src/main/metaconfig/keepalived/main.tt
ncm-metaconfig/src/main/metaconfig/keepalived/pan/config.pan
ncm-metaconfig/src/main/metaconfig/keepalived/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/keepalived/tests/profiles/config.pan
ncm-metaconfig/src/main/metaconfig/keepalived/tests/regexps/config/base
ncm-metaconfig/src/main/metaconfig/keepalived/track_script.tt
ncm-metaconfig/src/main/metaconfig/keepalived/virtual_ipaddress.tt
ncm-metaconfig/src/main/metaconfig/keepalived/vrrp_instance.tt
ncm-metaconfig/src/main/metaconfig/keepalived/vrrp_script.tt
ncm-metaconfig/src/test/perl/service-keepalived.t

Adds support for Keepalived to provide floating IP Addresses for use in Load Balancers

ncm-metaconfig: Add support for keepalived

---

ncm-authconfig/src/main/pan/components/authconfig/schema.pan
ncm-spma/src/main/pan/components/spma/schema.pan
ncm-ssh/src/main/pan/components/ssh/schema.pan

Standardise on new type from pan/legacy
quattor/template-library-core#111 introduced a common type for the variously named versions of a string containing either yes or no, this switches the components to use the new common version rather than their own differently named types.
It does not yes address the components that define types of string with a validation rule to essentially do the same thing, but without defining an explicit type.
Turns out coding on a train isn't that easy... just left Stirling, next stop Gleneagles.

ncm-*: Remove variants of yesno pseudo-boolean

---

ncm-symlink/src/main/perl/symlink.pm

If the symlink exists and points to the right location then do nothing and log
success.

ncm-symlink: do not make changes if symlink is correct

---

ncm-nfs/src/test/perl/compare.t
ncm-postgresql/src/main/resources/tests/regexps/main_config/value
ncm-postgresql/src/test/perl/01-tt.t
ncm-spma/src/test/perl/yum-make-cache.t

Handle ncm-postgres unittest failure due to new json_typed default ; and prepare ncm-spma and ncm-nfs for new buildtools

Unittest hotfixes

---

ncm-metaconfig/src/main/metaconfig/httpd/2.4/tests/profiles/krb5_profiles.pan
ncm-metaconfig/src/main/metaconfig/httpd/2.4/tests/profiles/krb5_sunstone.pan
ncm-metaconfig/src/main/metaconfig/httpd/2.4/tests/regexps/krb5_profiles/base
ncm-metaconfig/src/main/metaconfig/httpd/2.4/tests/regexps/krb5_sunstone/base
ncm-metaconfig/src/main/metaconfig/httpd/config/ssl_nss.tt
ncm-metaconfig/src/main/metaconfig/httpd/config/vhost.tt
ncm-metaconfig/src/main/metaconfig/httpd/pan/schema.pan

Add support for GSSAPI auth and example/unittests of apache config for retrieving profiles using kerberos

ncm-metaconfig: httpd support GSSAPI auth

---

ncm-filesystems/pom.xml

ncm-filesystems: pom.xml fix rpmlint 'description too long' error

---

ncm-spma/pom.xml

Allows autogenerated rpm dependencies for perl modules
Fixes rpmlint error due to spma-run being a script in a module location with 644 permission
Related to #764

ncm-spma: remove ips.pm and spma-run from (linux) rpmbuild 

---

ncm-metaconfig/src/main/metaconfig/lmod/scDescript.tt
ncm-metaconfig/src/main/metaconfig/lmod/tests/regexps/default/base

Values without quotes generates an invalid lmod rc file.

ncm-metaconfig: lmod: scDescript needs quoted values

---

ncm-filecopy/src/main/perl/filecopy.pod

The config value in the second example needs double quotes for the escape character to work

ncm-filecopy: Update filecopy.pod example to make it work

---

ncm-opennebula/src/main/perl/opennebula.pm
ncm-opennebula/src/test/perl/datastore.t
ncm-opennebula/src/test/perl/host.t
ncm-opennebula/src/test/perl/user.t

New RPCClient.pm generates less calls to RPC endpoint. This PR updates RPC unittests to use this new version.

ncm-opennebula: Fix RPC history

---

ncm-nss/src/main/perl/nss.pm

This is a very simple change we'd like in 16.4. I have a another branch that replaces LC::Check with FileWriter and includes unit tests which I can push for 16.6.

ncm-nss: wait for nscd to restart before returning

---

ncm-named/src/main/pan/components/named/schema.pan
ncm-resolver/src/main/pan/components/resolver/schema.pan

All supported resolvers (GNU/glib/BIND and Solaris) support a maximum of:
* Three nameservers
* Six search domains with a total of 256 characters
This also switches the plain strings to network types.
Small chance of backwards incompatibility.
Fixes #785.

Resolver list lengths

---

ncm-metaconfig/src/main/metaconfig/ganesha/pan/config_ces.pan

add dummy file to use ganesha with gpfs ces (Cluster Export Services)
With GPFS, you can configure a subset of nodes in the cluster to provide a highly available solution for exporting GPFS file systems by using the Network File System (NFS), Server Message Block (SMB), and Object protocols. The participating nodes are designated as Cluster Export Services (CES) nodes or protocol nodes. The set of CES nodes is frequently referred to as the CES cluster.

ncm-metaconfig: ganesha: add config_ces

---

ncm-spma/src/main/pan/components/spma/software.pan

ncm-spma: software repository protocol url should be a software_repository_url

---

ncm-metaconfig/src/main/perl/metaconfig.pm
ncm-metaconfig/src/test/perl/actions.t
ncm-metaconfig/src/test/perl/choose-module.t
ncm-metaconfig/src/test/perl/configure.t
ncm-metaconfig/src/test/perl/error.t
ncm-metaconfig/src/test/perl/json.t
ncm-metaconfig/src/test/perl/properties.t
ncm-metaconfig/src/test/perl/tiny.t
ncm-metaconfig/src/test/perl/tt.t

- Adapt unit tests to changes
- Fix #664

ncm-metaconfig: increase default verbosity to track changes/actions at info level

---

ncm-sudo/src/main/perl/sudo.pm

* The configurables 'mailsub' and 'secure_path' are present in the schema but not in the perl.
* This should not introduce any incompatibility, it is a bug fix.
* Discussed in #773.

ncm-sudo: missing elements in list of STRING_OPTS in sudo.pm

---

ncm-spma/src/main/pan/components/spma/config-ips.pan
ncm-spma/src/main/pan/components/spma/config-rpm.pan
ncm-spma/src/main/pan/components/spma/software.pan

Fixes #797.
`yumng` properties have no business being anywhere near `ips` either.

ncm-spma: Backport changes from reverting yumng schema

---

ncm-spma/src/main/pan/components/spma/config-rpm.pan

config-rpm: do not define groups/names/yumng by default

---

ncm-afsclt/pom.xml
ncm-afsclt/src/main/pan/components/afsclt/schema.pan
ncm-afsclt/src/main/perl/afsclt.pm
ncm-afsclt/src/main/perl/afsclt.pod
ncm-afsclt/src/test/perl/configure_afsd_args.t
ncm-afsclt/src/test/perl/configure_cache.t
ncm-afsclt/src/test/perl/configure_cell.t
ncm-afsclt/src/test/perl/configure_cellservdb.t
ncm-afsclt/src/test/perl/configure_thesecells.t
ncm-afsclt/src/test/resources/automatic.pan
ncm-afsclt/src/test/resources/automatic_nocachemount.pan
ncm-afsclt/src/test/resources/explicit.pan

ncm-afsclt: fix handling of size AUTOMATIC

---

ncm-afsclt/src/main/perl/afsclt.pm

The updates to afsclt seem to work fine here. I just noticed a perl warning while running ncm-ncd.

ncm-afsclt: Fix warning caused redeclaration of variable with my.

---

ncm-sudo/src/main/pan/components/sudo/schema.pan
ncm-sudo/src/main/perl/sudo.pm

* The configurable 'visiblepw' is a default setting in the /etc/sudoers file as installed via the RPM in Scientific Linux 5,6&7.
* Having this option added to ncm-sudo will allow a system administrator to reconstruct the /etc/sudoers file if they so wished. This is currently not possible.
* This should not introduce any incompatibility, it is a simple enhancement.

ncm-sudo: add boolean option 'visiblepw' to ncm-sudo.

---

ncm-metaconfig/src/main/metaconfig/zkrsync/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/zkrsync/tests/profiles/testsession.pan
ncm-metaconfig/src/main/metaconfig/zkrsync/tests/regexps/testsession

adding the timeout option for rsync to the zkrsync config file

ncm-metaconfig: zkrsync: add timeout option

---

ncm-metaconfig/src/main/metaconfig/beats/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/beats/tests/profiles/filebeat.pan
ncm-metaconfig/src/main/metaconfig/beats/tests/regexps/filebeat/base

ncm-metaconfig: beats: allow more than one output

---

ncm-afsclt/src/main/perl/afsclt.pm

Found a small issue with @jouvin's refactoring - a missing use FileReader (it didn't use FileReader before). I think this only happens if you run ncm-afsclt alone (as we do at one point in our build) presumably because another components hasn't loaded it already.
I've changed the new use of FileReader to a FileEditor with explicit cancel so it's essentially the same, and consistent with another read in the component. Sorry, we have an old version of CAF on older builds, they will hopefully go away soon.
Ensure the title of this pull-request starts with the component name followed by a colon, e.g.
> ncm-example: demonstrate what titles should look like
* What backwards …

ncm-afsclt: use FileEditor not FileReader (for old CAF).

---

ncm-metaconfig/src/main/metaconfig/ptpd/pan/schema.pan

ncm-metaconfig: ptpd: add extra attributes to deal with large clock skew

---

ncm-afsclt/src/main/perl/afsclt.pod

- markdown does not like underscores in (what it thinks are) paths, escape them.
- removed superfluous info.

ncm-afsclt: documentation cleanup

---

ncm-authconfig/src/main/perl/authconfig.pod

cleanup for consistency.
Removed link to CERN wiki as it requires authentication.

ncm-authconfig: minor documentation fixes

---

ncm-download/src/main/pan/components/download/config.pan

After #833, a reference to a previous template still existed

ncm-download: config-rpm is not part of the templates anymore

---

ncm-cron/pom.xml
ncm-cron/src/main/perl/cron.pod

Documentation fixes and moved a developer to ```pom.xml```.

ncm-cron: documentation fixes

---

ncm-metaconfig/src/main/metaconfig/cgroups/cgconfig.tt
ncm-metaconfig/src/main/metaconfig/cgroups/config/template.tt
ncm-metaconfig/src/main/metaconfig/cgroups/pan/cgconfig.pan
ncm-metaconfig/src/main/metaconfig/cgroups/pan/cgrules.pan
ncm-metaconfig/src/main/metaconfig/cgroups/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/cgroups/tests/profiles/cgconfig.pan
ncm-metaconfig/src/main/metaconfig/cgroups/tests/profiles/cgconfig_example2.pan
ncm-metaconfig/src/main/metaconfig/cgroups/tests/profiles/cgconfig_example3.pan
ncm-metaconfig/src/main/metaconfig/cgroups/tests/regexps/cgconfig/value
ncm-metaconfig/src/main/metaconfig/cgroups/tests/regexps/cgconfig_example2
ncm-metaconfig/src/main/metaconfig/cgroups/tests/regexps/cgconfig_example3

Also fixes the usage of correct `cgred` services for cgrules

ncm-metaconfig: cgroups: change default cgconfig location

---

ncm-fstab/src/main/perl/fstab.pod

Mainly removed links to CERN as it requires authentication.

ncm-fstab: clean up documentation

---

ncm-metaconfig/src/main/pan/components/metaconfig/schema.pan
ncm-metaconfig/src/test/perl/element.t
ncm-metaconfig/src/test/resources/element.pan

In particular useful to use `tiny` with lists of scalars
Requires https://github.com/quattor/CCM/pull/96

ncm-metaconfig: add joincomma and joinspace convert options

---

ncm-nfs/src/main/pan/components/nfs/schema.pan
ncm-nfs/src/main/perl/nfs.pm
ncm-nfs/src/test/perl/fstab.t
ncm-nfs/src/test/resources/fstab_simple.pan
ncm-nfs/src/test/resources/regexps/fstab

Adding the ability to add CephFS network shares into fstab using ncm-nfs.

ncm-nfs: add cephfs share type to NFS component schema

---

ncm-opennebula/src/main/pan/components/opennebula/schema.pan
ncm-opennebula/src/main/resources/tests/regexps/sunstone/simple
ncm-opennebula/src/main/resources/tests/regexps/sunstone/sunstone_template

* Fix #872 : env option is missing in opennebula_sunstone schema
Include a missing value in `sunstone-server.conf`

ncm-opennebula: opennebula schema minor fix

---

ncm-libvirtd/src/main/perl/libvirtd.pod

Codify options to make sure pipe is not interpreted as a table.

ncm-libvirtd: documentation clean up

---

ncm-iptables/src/main/perl/iptables.pod

- some structure work
- cannot find extra documentation mentioned, so removed mentioning of it
- some minor spelling fixes.

ncm-iptables: clean up documentation

---

ncm-ccm/src/main/perl/ccm.pm

ncm-ccm: add missing "use CAF::FileReader"
Component fails if the noquattor file is present, and some other component has not already loaded FileReader (eg. only this compoent was run).
None.

ncm-ccm: add missing "use CAF::FileReader"

---

ncm-network/src/main/perl/network.pod

ncm-network: documentation cleanup

---

ncm-gpfs/src/main/perl/gpfs.pm

ncm-gpfs does not need to fail because of unrecognized package gpfs.hdfs-protocol

ncm-gpfs: add new hdfs-protocol package to GPFSRPMS

---

ncm-download/src/main/perl/download.pm

The KRB5CCNAME environment variable is set using local scope inside an
if block. This means the environment variable is not set for the curl
invocation outside, and as such GSSAPI fails.
Declare $ENV{KRB5CCNAME} as local variable outside in the right scope.
None.

ncm-download: fix GSSAPI on GET requests.

---

ncm-download/src/main/perl/download.pm
ncm-download/src/test/perl/download.t
ncm-download/src/test/resources/download.pan

Bug in the proxy handling. The list of proxies is passed to a function
by reference, which is intended to rotate the list.
While the intention (and previous behaviour) was to put $proxy back
into the original list, either at the front or at the end, now it creates
a new list instead while the original one gets shorter...
None.

ncm-download: fix proxy handling.

---

ncm-symlink/src/main/perl/symlink.pod

fix:
- structure
- typo's
- examples spacing
- too long lines

ncm-symlink: clean up documentation

---

ncm-resolver/src/main/perl/resolver.pod

Did some minor clean up.
@jrha @ned21 this documentation contains a disclaimer (which I probably can't remove) and a reference to [http://eu-datagrid.web.cern.ch/eu-datagrid/license.html](http://eu-datagrid.web.cern.ch/eu-datagrid/license.html).
to adhere to point 2 I can add an acknowledgement in the pod stating:
```
"This product includes software developed by the EU DataGrid (http://www.eu-datagrid.org/)."
```
But I don't know if this actually is enough to be compliant as most of the reference and disclaimer will never show up on a website or documentation as they are in comments.
Thoughts?

ncm-resolver: clean up documentation

---

ncm-fstab/src/main/perl/fstab.pm

Since the last time I looked at this component, the call to LC::File::makedir has been replaced with LC::Check::directory, so it should be possible to enable NoAction support.
Component supports NoAction but needs flag set.
None.

ncm-fstab: enable NoAction support.

---

ncm-ccm/src/main/pan/components/ccm/schema.pan

We would like to start using the purge_time config setting but it's missing from the schema.
None.

ncm-ccm: support purge_time config setting.

---

ncm-metaconfig/src/main/metaconfig/nginx/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/nginx/ssl.tt

* Fix #876 : ssl.tt file generates an empty ssl_client_certificate value

ncm-metaconfig: nginx fix ssl conf

---

ncm-metaconfig/src/main/metaconfig/ncm-ncd/pan/schema.pan

Allow to configure new options introduced by https://github.com/quattor/ncm-ncd/pull/88

metaconfig: service ncm-ncd: add new config options

---

ncm-accounts/src/main/pan/components/accounts/schema.pan
ncm-amandaserver/src/main/pan/components/amandaserver/schema.pan
ncm-cups/src/main/pan/components/cups/schema.pan
ncm-iptables/src/main/pan/components/iptables/schema.pan
ncm-nscd/src/main/pan/components/nscd/schema.pan

Fixes #752 as described therein.

ncm-accounts, ncm-amandaserver, ncm-cups, ncm-iptables, ncm-nscd: Use legacy type for simple yes/no strings

---

ncm-network/src/main/perl/network.pm

Removes the utterly useless "Some more debug info" message that irritates me so much.
We should probably do something about the multi line message after it as well, but this will do for now.

ncm-network: Remove useless log message

---

ncm-aiiserver/src/main/perl/aiiserver.pod

ncm-aiiserver: fix documentation link issue

---

ncm-directoryservices/src/main/perl/directoryservices.pm
ncm-mcx/src/main/perl/mcx.pm

ncm-mcx, ncm-directoryservices: Remove unescape method from NCM::Component

---

ncm-cdp/src/main/pan/components/cdp/schema.pan

A new "hostname" option has been introduced by https://github.com/quattor/cdp-listend/pull/16 to specify the interface to bind. Fixes #944 (requires quattor/cdp-listend#16 for the underlying support).
This is a backward compatible change.

ncm-cdp : Update ncm-cdp schema to support hostname

---

ncm-metaconfig/src/main/metaconfig/httpd/2.2/tests/regexps/httpd_conf_el6/base
ncm-metaconfig/src/main/metaconfig/httpd/2.4/tests/regexps/httpd_conf_el7/base
ncm-metaconfig/src/main/metaconfig/httpd/pan/schema.pan

Disable server settings that publish detailed version information and allow for separate ciphersuite settings like `list("TLSv1", "!RC4", "!LOW", "!aNULL", "!eNULL", "!MD5", "!EXP", "!3DES", "!IDEA")`

ncm-metaconfig: service httpd: tighten security related settings

---

ncm-authconfig/src/main/pan/components/authconfig/sssd/ipa.pan
ncm-metaconfig/src/main/metaconfig/ctdb/pan/schema.pan
ncm-network/src/main/pan/components/network/core-schema.pan

Make use of `valid_interface` type introduced in quattor/template-library-core#135,
hence requires quattor/template-library-core#135.

ncm-network, ncm-authconfig, ncm-metaconfig: Use new valid_interface type

---

ncm-gpfs/src/main/perl/gpfs.pm
ncm-gpfs/src/test/perl/rpms.t

the gpfs component removes the update packages and installs the base packages, but didn't reinstall the update packages, therefore, this is not installed correctly in the ks-post-reboot phase

ncm-gpfs: reinstall gpfs update packages after base

---

ncm-useraccess/src/test/perl/kerberos.t

Unittest fail with usual 'throw_error on DESTROY'

ncm-useraccess: close dangling FileWriter instance before DESTROY

---

ncm-metaconfig/src/main/metaconfig/opennebula/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/opennebula/tests/profiles/config.pan
ncm-metaconfig/src/main/metaconfig/opennebula/tests/regexps/config/base
ncm-metaconfig/src/main/metaconfig/opennebula/tests/regexps/config/rpc

Include a CA option to enable secure RPC connections.
Resolves: #1015

ncm-metaconfig: opennebula Include CA option

---

ncm-grub/src/main/perl/grub.pm
ncm-grub/src/test/perl/methods.t

@stdweird's nice refactor of ncm-grub, mostly uses grubby commands now, but as pointed out the password support still manipulates grub.conf directly, which will not work with grub2.
This is a simple change to use /boot/grub2/user.cfg and the different syntax if /boot/grub2 is present (other suggestions welcome).
The serial console stuff is still todo.

ncm-grub: support settings passwords 

---

ncm-fstab/src/main/perl/fstab.pm
ncm-fstab/src/test/perl/protected.t

Some changes needed to subclass ncm-filesystems from ncm-fstab. So also needed for the tests to run for #985

ncm-fstab: pass tree instead of config

---

ncm-filesystems/src/main/perl/filesystems.pm

Fixes failing tests caused by removal of `partition_compare` in quattor/ncm-lib-blockdevices#80.

ncm-filesystems: Use partition_sort instead of sorting partition_compare

---

ncm-metaconfig/src/main/metaconfig/devicemapper/multipath/attribute.tt
ncm-metaconfig/src/main/metaconfig/devicemapper/multipath/device.tt
ncm-metaconfig/src/main/metaconfig/devicemapper/pan/schema.pan

`fast_io_fail_tmo` is not boolean
`blacklist` `product` is not mandatory

ncm-metaconfig: devicemapper: fix multipath config

---

ncm-authconfig/src/main/pan/components/authconfig/sssd.pan

previous default `0x0210` loglevel makes no sense (fatal failure and function data). it is probably some miscaclculation/misconversion.
the new default logs fatal/critical/serious/minor failures and configuration data on startup. it's not too verbose, log files stay reasonably sized

ncm-authconfig: sssd: use sensible default debug_level

---

ncm-opennebula/src/main/pan/quattor/aii/opennebula/rpms.pan

This PR includes the missing rpm template for ONE AII

ncm-opennebula: Add aii component rpm

---

ncm-opennebula/src/main/perl/OpenNebula/Ceph.pm
ncm-opennebula/src/main/perl/OpenNebula/Host.pm
ncm-opennebula/src/main/perl/OpenNebula/Image.pm
ncm-opennebula/src/main/perl/OpenNebula/Network.pm
ncm-opennebula/src/main/perl/OpenNebula/Server.pm
ncm-opennebula/src/main/perl/OpenNebula/VM.pm

While building a new version of the documentation I found a small issue which will result in dead links. This fixes that.

ncm-opennebula: Documentation fixes

---

ncm-filesystems/src/main/pan/components/filesystems/schema.pan
ncm-filesystems/src/main/perl/filesystems.pm
ncm-filesystems/src/main/perl/filesystems.pod
ncm-filesystems/src/test/perl/00-load.t
ncm-filesystems/src/test/perl/configure.t
ncm-filesystems/src/test/perl/configure_create.t
ncm-filesystems/src/test/perl/data.pm
ncm-filesystems/src/test/resources/configure.pan
ncm-filesystems/src/test/resources/configure_create.pan
ncm-filesystems/src/test/resources/devices.pan
ncm-filesystems/src/test/resources/fstab_regextest
pom.xml

Use fstab methods for filesystems
Filesystems is written to also include ncm-fstab functionality (So if you want to use filesystems somewhere, you don't need fstab) .
If you would set manage_blockdevs to false, it would do the same as ncm-fstab

ncm-filesystems: rewrite to reuse ncm-fstab code

---

ncm-freeipa/src/test/perl/mock_rpc.pm

Unittests fail on new jenkins environment because there is a mixed JSON::XS and JSON::PP environment (due to loading of `Devel::Cover`).

ncm-freeipa: mock_rpc: handle JSON boolean string conversion with mixed JSON::PP and JSON::XS environment

---

ncm-network/src/main/perl/network.pm
ncm-network/src/test/perl/bridge.t
ncm-network/src/test/perl/ipv6.t
ncm-network/src/test/perl/ovs.t
ncm-network/src/test/perl/simple.t

ncm-network: device name regex: allow function and device in PCI name

---

ncm-iptables/src/main/perl/iptables.pm
ncm-systemd/src/main/perl/Systemd/Service/Chkconfig.pm
ncm-systemd/src/main/perl/Systemd/Service/Unit.pm
ncm-systemd/src/main/perl/Systemd/UnitFile.pm
ncm-systemd/src/test/perl/service-unit.t
ncm-systemd/src/test/perl/service.t
ncm-systemd/src/test/perl/unitfile.t

After https://github.com/quattor/CCM/pull/162 usage of `CCM::Resource` and direct class testing with old name are not supported anymore

CCM cleanup fallout

---

ncm-postgresql/src/main/pan/components/postgresql/schema.pan

This will start warning about "checkpoint_segments" as it is deprecated starting postgres version 9.5.

ncm-postgresql: Add warning about deprecated configuration options.

---

ncm-icinga/src/main/pan/components/icinga/schema.pan

ido2db will not fail if the options are present but will ignore them. Start warning about it. Also make it optional.

ncm-icinga: start warning about deprecated config options.

---

ncm-icinga/src/main/pan/components/icinga/functions.pan
ncm-icinga/src/main/pan/components/icinga/schema.pan

Some characters are not accepted as a service name ```,:;!?&``` etc. Letting these through to the config will cause icinga to refuse to restart.

ncm-icinga: check service names for invalid characters

---

ncm-directoryservices/src/main/pan/components/directoryservices/schema.pan
ncm-fmonagent/src/main/pan/components/fmonagent/schema.pan
ncm-mcx/src/main/pan/components/mcx/schema.pan

Throw deprecation if the following components are initialised:
* ncm-directoryservices
* ncm-fmonagent
* ncm-mcx
This is the first step towards #1027.

ncm-directoryservices ncm-fmonagent ncm-mcx: Deprecate with warnings

---

ncm-spma/src/main/pan/components/spma/ips/config.pan
ncm-spma/src/main/pan/components/spma/schema.pan
ncm-spma/src/main/perl/spma/ips.pm
ncm-spma/src/main/perl/spma/ips.pod

Where it is possible to use the `pkg exact-install` command to create a new Solaris boot environment with an exact list of packages, then use it as it is faster.  Where it is not possible to do this, revert to the previous logic where the package list is determined by comparing with a temporary package image directory.
This patch also adds support for whitelists which is a list of packages that are permitted on the system even if they have not been explicitly requested and even if `userpkgs` is set to `no`.

ncm-spma: support Solaris pkg exact-install and whitelists

---

ncm-filecopy/src/main/perl/filecopy.pm

Remove the hardcoded path to  /software/components/filecopy to allow subclassing the component
Fixes #1098.

ncm-filecopy: remove hardcoded path to component

---

ncm-aiiserver/src/main/pan/components/aiiserver/schema.pan

Use appropriate, more restricted, type rather than strings, when possible.

ncm-aiiserver schema cleanup

---

ncm-authconfig/src/main/pan/components/authconfig/schema.pan
ncm-authconfig/src/main/perl/authconfig.pm

This appears to never have been used and looks like copypasta.
As discussed in #1143.

ncm-authconfig: Deprecate unused startstop property

---

ncm-metaconfig/src/main/metaconfig/devicemapper/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/devicemapper/tests/profiles/multipath.pan
ncm-metaconfig/src/main/metaconfig/devicemapper/tests/regexps/multipath/base

Requires recent devicemapper (see https://rhn.redhat.com/errata/RHEA-2017-1300.html)

ncm-metaconfig: devicemapper: support (recent) max_sectors_kb option

---

ncm-metaconfig/src/main/metaconfig/kibana/pan/config.pan
ncm-metaconfig/src/main/metaconfig/kibana/tests/profiles/config.pan
ncm-metaconfig/src/main/metaconfig/kibana/tests/regexps/config/base

Since kibana 5.0 release, kibana configuration from the rpm package is under /etc
Partial fix of #997

ncm-metaconfig: kibana: configuration location is now under /etc

---

ncm-mysql/src/main/pan/components/mysql/schema.pan

I ran into a (luckily test) server dropping and recreating the database everytime ncm-mysql ran because this is set to false.
I do believe the use case of recreating every time is less likely than setting it up once. So setting it to true is more "what somebody would expect" IMHO.

ncm-mysql: set initOnce to true by default

---

ncm-metaconfig/src/main/metaconfig/httpd/2.4/tests/profiles/krb5_profiles.pan
ncm-metaconfig/src/main/metaconfig/httpd/2.4/tests/profiles/krb5_sunstone.pan
ncm-metaconfig/src/main/metaconfig/httpd/2.4/tests/profiles/struct/nss_conf_el6.pan
ncm-metaconfig/src/main/metaconfig/httpd/2.4/tests/regexps/krb5_profiles/base
ncm-metaconfig/src/main/metaconfig/httpd/2.4/tests/regexps/krb5_sunstone/base
ncm-metaconfig/src/main/metaconfig/httpd/pan/schema.pan

* SEED and CAMELLIA are also insecure ciphersuites, you shouldn't be allowed to explicitly turn them on.
* This may break for people who have these turned on, they probably shouldn't.
Replaces #983.

ncm-metaconfig: don't allow specific turning on of SEED and CAMELLIA

---

ncm-syslog/src/main/pan/components/syslog/schema.pan
ncm-syslog/src/test/perl/configure.t
ncm-syslog/src/test/resources/basic.pan

Fixes problem reported in 17.7.0-rc1 (quattor/release#300).

ncm-syslog: Expand facility regex to allow comma seperated lists

---

ncm-syslog/src/main/perl/syslog.pm
ncm-syslog/src/test/perl/configure.t

This fixes the proliferation of blank lines seen in quattor/release#301

ncm-syslog: Start with an empty list in edit mode

---

ncm-systemd/src/main/resources/custom/tests/regexps/unitfile0/value
ncm-systemd/src/main/resources/regular/tests/regexps/unitfile0/value

Just another typo that bothered me.
uniffile → unitfile

ncm-systemd: fix typo in test description

---

ncm-amandaserver/src/main/perl/amandaserver.pm
ncm-ceph/src/main/perl/Ceph/daemon.pm
ncm-chkconfig/src/main/perl/chkconfig.pm
ncm-cups/src/main/perl/cups.pm
ncm-dirperm/src/main/perl/dirperm.pm
ncm-filecopy/src/main/perl/filecopy.pm
ncm-ganglia/src/main/perl/ganglia.pm
ncm-hostsaccess/src/main/perl/hostsaccess.pm
ncm-icinga/src/main/perl/icinga.pm
ncm-ipmi/src/main/perl/ipmi.pm
ncm-ldconf/src/main/perl/ldconf.pm
ncm-mysql/src/main/perl/mysql.pm
ncm-named/src/main/perl/named.pm
ncm-named/src/test/perl/configure.t
ncm-named/src/test/perl/get_named_root_dir.t
ncm-openldap/src/main/perl/openldap.pm
ncm-pam/src/main/perl/pam.pm
ncm-pnp4nagios/src/main/perl/pnp4nagios.pm
ncm-postfix/src/main/perl/postfix.pm
ncm-postgresql/src/main/perl/postgresql.pm
ncm-postgresql/src/test/perl/configure.t
ncm-postgresql/src/test/perl/iam.t
ncm-profile/src/main/perl/profile.pm
ncm-puppet/src/main/perl/puppet.pm
ncm-symlink/src/main/perl/symlink.pm
ncm-sysconfig/src/main/perl/sysconfig.pm
ncm-sysctl/src/main/perl/sysctl.pm
ncm-sysctl/src/test/perl/configure.t

Fixes #1083 
(except for deprecated `directoryserver` and `mcx`; and `cron`, `metaconfig` and `network` that have existing cleanup PRs)

Escape / unescape functions from CCM::Path

---

ncm-authconfig/src/main/pan/components/authconfig/schema.pan

The property served no purpose and was deprecated in c5be6d26aa802584b0ecaedcea4d5e99b247f9d7,
this completes the cleanup and removal.
Fixes #1145 (which in turn resolves #1143).

ncm-authconfig: Remove deprecated startstop property

---

ncm-accounts/src/main/pan/components/accounts/sysgroups.pan
ncm-accounts/src/main/pan/components/accounts/sysusers.pan

`colord` (standard) package creates a `colord` user and group that are not protected in `ncm-accounts`. Hence, they are removed by the first run of `ncm-accounts` after the package installation.

ncm-accounts: add colord to protected user/group list

---

ncm-accounts/src/main/pan/components/accounts/functions.pan

The is_user_or_group() function needs to take into account that some
sites use mechanisms other than ncm-accounts to provision users and
groups. Following the pattern introduced into ncm-ccm, allow the
function to be called but always return true if the
/software/components/accounts tree is not present.
Fixes #1166

ncm-accounts: is_user_or_group function can be used without component

---

ncm-accounts/src/main/pan/components/accounts/functions.pan

* Allow `is_user_or_group` function to be annotated   
The annotation parser does not allow for anything other than whitespace
between a set of annotation blocks and the item being annotated. The
semicolons here were preventing the annotation from being associated with
the function and were effectively "stealing" the annotations.
* Fix whitespace lint around operators and semicolons

ncm-accounts: Fix annotations and whitespace lint

---

ncm-metaconfig/src/main/metaconfig/beats/pan/gpfsbeat.pan
ncm-metaconfig/src/main/metaconfig/beats/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/beats/tests/profiles/gpfsbeat.pan
ncm-metaconfig/src/main/metaconfig/beats/tests/regexps/gpfsbeat/base

Adding a schema and a bind to the schema for the gpfsbeat service, used to push GPFS related information to logstash and/or elastiscsearch.
- Requires tests

ncm-metaconfig: gpfsbeat schema

---

ncm-metaconfig/src/main/metaconfig/logstash/pan/config_5.0.pan
ncm-metaconfig/src/main/metaconfig/logstash/pan/daemon_5.0.pan
ncm-metaconfig/src/main/metaconfig/logstash/pan/schema_5.0.pan

Adding a schema and a bind to it for `/etc/logstash/logstash.yml` to allow configuring the logstash service for logstash >= 5.0.
- This should be rebased on master once #1028 has been merged since it requires the distinction between 1.2, 2.0 and 5.0 logstash services.
- Requires tests

WIP ncm-metaconfig: support for logstash yml

---

ncm-network/src/main/perl/network.pm

Only `CAF::` is used, all should be noaction safe
Fixes #1086

ncm-network: NoActionSupported

---

ncm-download/src/main/pan/components/download/schema.pan
ncm-download/src/main/perl/download.pm

kinit -k, called by get_gss_token, sometimes may need exstra arguments
passed in. Introducing kinit_args in the $tree makes it possible.
The change does not introduce any backwards incompatibilities - if kinit_args is not set, the default "kinit -k" will be called.

ncm-download: kinit: add a possibility to pass arguments

---

ncm-nfs/src/main/pan/components/nfs/schema.pan
ncm-nfs/src/main/perl/nfs.pm
ncm-nfs/src/test/perl/configure.t
ncm-nfs/src/test/resources/configure_nomounts.pan

Allows ncm-fstab to coexist with nfs server managed by ncm-nfs.

ncm-nfs: when no mounts are defined, do not process any mounts

---

ncm-pam/src/main/pan/components/pam/config.pan

New function which mirrors the ability to add netgroups to the components/pam/access with one that can handle unix groups.
Also some small clean ups to remove un-necessary returns().

ncm-pam: new function pam_add_access_group

---

ncm-metaconfig/src/main/metaconfig/ganesha/2.2/main.tt
ncm-metaconfig/src/main/metaconfig/ganesha/2.2/tests/regexps/config2/export

gpfs ces need CLIENT and FSAL blocks last in the export config

ncm-metaconfig: ganesha: make exports usable for ces

---

ncm-gpfs/src/main/perl/gpfs.pm
ncm-gpfs/src/test/perl/base.t

genkeyData1 had suffix 1 because it was first generation of key. GPFS increases this when a new key is generated, and uses this when it is committed. This fixes it to use the right key and the right location

ncm-gpfs: fix keydata files

---

ncm-metaconfig/src/main/metaconfig/logstash/pan/schema.pan

Required to make the template-library-core unittests pass

ncm-metaconfig: service logstash: remove include of non-existing version template

---

ncm-authconfig/src/main/pan/components/authconfig/sssd.pan
ncm-authconfig/src/main/pan/components/authconfig/sssd/ldap.pan
ncm-authconfig/src/main/pan/components/authconfig/sssd/user.pan
ncm-authconfig/src/main/resources/tests/profiles/basic.pan
ncm-authconfig/src/main/resources/tests/regexps/basic/value

- Make most inputs optional
- Add sssd_auth_provider_string that accepts krb5 but not simple
- Add "reconnection_retries" in sssd_pam and sssd_nss
- Make most inputs optional n sssd_global, sssd_pam and sssd_nss
- Add  "reconnection_retries" in sssd_domain
- Make some inputs optional
- Remove use_object_class in sssd_ldap because this option is not available in the SSSD configuration but there is a user_object_class option.
- Add object_class and name in sssd/user
- Make most inputs optional
- Make ldap_uri optional

ncm-authconfig : Change auth_provider, reconnection_retries, user object_class and ldap_uri

---

ncm-puppet/src/main/pan/components/puppet/schema.pan
ncm-puppet/src/main/perl/puppet.pm
ncm-puppet/src/test/perl/apply.t
ncm-puppet/src/test/perl/functions.t
ncm-puppet/src/test/perl/install_modules.t

the previous version of the ncm-puppet was not compliant with puppet v4 and v5. In particular, as things in such version have been heavily reorganized (executable, configuration files, modules, manifests locations have changed, for example) it was necessary to update the schema and the component introducing more flexibility.
There is no real backward incompatibility. We added new fields in the schema but the default values of such fields are those used for puppet v3 (so, those that were hardcoded in the old version of the component).

ncm-puppet: puppet v4 and v5 compatibility

---

ncm-nfs/src/main/pan/components/nfs/schema.pan
ncm-nfs/src/main/perl/nfs.pm
ncm-nfs/src/test/perl/fstab.t
ncm-nfs/src/test/resources/fstab_simple.pan
ncm-nfs/src/test/resources/regexps/fstab

Tested @ugent, see also http://docs.ceph.com/docs/master/cephfs/fstab/

ncm-nfs: mount type for cephfs is ceph

---

ncm-openstack/src/main/pan/components/openstack/glance.pan
ncm-openstack/src/main/pan/components/openstack/neutron.pan
ncm-openstack/src/main/pan/components/openstack/nova.pan
ncm-openstack/src/main/pan/components/openstack/schema.pan

The Glance, Neutron and Nova schema use the `openstack_keystone_authtoken` type
which is defined in the Keystone schema.
The missing dependency is causing tests on **template-library-core** to fail.
The root type is defined as the reverse of what the built-tools templating generates, so fix that too.
Hopefully shouldn't cause conflicts with #1192.

ncm-openstack: Schema fixes

---

ncm-metaconfig/src/main/metaconfig/rsyslog/pan/common.pan
ncm-metaconfig/src/main/metaconfig/rsyslog/pan/schema.pan

Cleaner and allows for simpler testing when copied to core template library.

ncm-metaconfig: rsyslog: Move common parts of schema to a common template

---

pom.xml

Builds try to connect to it and hang for a long time before the connection times out.

pom: Remove references to decomissioned stratuslab-srv01

---

ncm-cron/src/main/pan/components/cron/schema.pan

Add a function to validate the contents of cron timing fields.
I've got tired of finding cron jobs which are not running due to simple mistakes such as entering day names in the `day` field rather than the `weekday` field due to the almost complete lack of any validation on this component.
This could get pretty complex and most of the public domain regexes I found do a poor job of covering the accepted syntax, so for now we'll just perform some basic sanity checking on numbers and text found in the fields.
While we're touching this, also improve the annotations a bit.

ncm-cron: Implement some validation of cron timing fields

---

ncm-metaconfig/src/main/metaconfig/udev/blockdev.tt
ncm-metaconfig/src/main/metaconfig/udev/pan/blockdev_run.pan
ncm-metaconfig/src/main/metaconfig/udev/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/udev/tests/profiles/blockdev_run.pan
ncm-metaconfig/src/main/metaconfig/udev/tests/regexps/blockdev_run/base

configure udev to run scripts for certain blockdevices

ncm-metaconfig: udev : add blockdev udev rules

---

ncm-metaconfig/src/main/metaconfig/beats/pan/schema.pan

By default `name` is not needed, but then it gets the hostname as value, which is likely not what you want. This allows us to set the desired beat name in the configuration.

ncm-metaconfig: add name config option for beats

---

ncm-cron/src/main/pan/components/cron/schema.pan
ncm-cron/src/main/perl/cron.pm
ncm-cron/src/test/resources/cron_syslog-common.pan

Resolves issue reported in quattor/release#314 caused by #1222.
Should really be replaced by use of `smear` in `timing` structure, but there is too much code in the wild using `AUTO` to remove support for it right now. #1227 opened to track this in the longer term.

ncm-cron: Support magic AUTO value in minutes field of frequency

---

ncm-cron/src/main/pan/components/cron/schema.pan
ncm-cron/src/test/resources/cron_syslog-common.pan

The `*-,` part was being treated as a range of characters between `*` and `,` which is obviously nonsense.

ncm-cron: Escape hyphen as we don't want it to be treated as a range

---

ncm-nfs/src/main/perl/nfs.pm
ncm-nfs/src/test/perl/fstab.t

fix a bug where every run of ncm-nfs would create an additional entry in fstab for ceph mounts because of wrong match regex

ncm-nfs: fix ceph fs type in nfs.pm

---

ncm-metaconfig/src/main/perl/metaconfig.pm

ncm-metaconfig: do not pass undef values to FileWriter

---

ncm-metaconfig/src/test/perl/aii_command.t
ncm-metaconfig/src/test/perl/configure.t

Fixes failure of nightly builds with a user named `foo1234`

ncm-metaconfig: aii_command unittest: make the test more robust

---

ncm-sudo/src/main/pan/components/sudo/validation.pan

Aliases are dictionaries of lists with the alias name as the key, but the validation code was treating them as a lists of alias names, so bad times ensued.
Fixes compilation problems with example template library.

ncm-sudo: Test names of alias list entries, rather than list itself

---

ncm-cron/src/main/pan/components/cron/config.pan

- /system/archetype/os is now a dict instead of a string
**Required for Aquilon support** (see https://github.com/quattor/template-library-core/pull/177).
Fixes #1281

ncm-cron: fix test of /system/archetype/os

---

ncm-cron/src/main/pan/components/cron/config.pan

The schema change which triggered this was wrong and will be reverted in quattor/template-library-core#181.
Reverts #1282.

Revert "ncm-cron: fix test of /system/archetype/os"

---

ncm-useraccess/src/main/perl/useraccess.pod

I believe that what the documentation states about disabling/locking users is bad practice. see #1289 .

ncm-useraccess: remove bad practice example from documentation

---

ncm-grub/src/main/pan/components/grub/schema.pan
ncm-grub/src/main/perl/grub.pm
ncm-grub/src/test/perl/methods.t
ncm-grub/src/test/resources/nopassword.pan

Removing a password previously set in grub.conf won't work.
CAF::FileEditor->remove_lines removes lines matching the first
parameter, but not the second parameter. The empty string ''
matches all lines, so it will never remove lines.
Replacing it with 'q(no good line)' as in the ncm-named/*/named.pm
will have the desired effect.
If someone was accidentally or deliberately relying on setting the password to 'disabled' in a template, NOT removing the password line from grub.conf, they may be affected by making it work as documented.
If they were using the "enabled=false" line as designed, it wouldn't have worked.

ncm-grub: remove password from grub.conf if disabled

---

ncm-systemd/src/main/perl/Systemd/Service.pm
ncm-systemd/src/main/perl/Systemd/Systemctl.pm
ncm-systemd/src/test/perl/cmddata.pm
ncm-systemd/src/test/perl/cmddata/service-systemctl_is_active_multi_user_target
ncm-systemd/src/test/perl/component.t
ncm-systemd/src/test/perl/service-component-chkconfig.t
ncm-systemd/src/test/perl/service.t

If ncm-systemd is called during boot or shut-down, then it should avoid
starting/stopping services itself, as that could interfere with the
standard ordering of events. E.g., on shut-down, it could start services
again which were just stopped.

ncm-systemd: Do not start/stop services during boot and shutdown

---

ncm-ssh/src/main/pan/components/ssh/schema-5.3.pan
ncm-ssh/src/main/pan/components/ssh/schema-7.4.pan
ncm-ssh/src/main/pan/components/ssh/schema.pan

Splits out the existing AuthorizedKeysCommand schema entries into their own type in a separate file which can then have different versions for different versions of openssh. This type is then included where the original entries were. 
This fixes #1237

ncm-ssh: schema update for changed AuthorizedKeysCommand* 

---

ncm-network/src/main/pan/components/network/core-schema.pan
ncm-network/src/main/pan/components/network/schema.pan
ncm-network/src/main/perl/network.pm
ncm-network/src/test/perl/dev2mac.t
ncm-network/src/test/perl/rename.t
ncm-network/src/test/perl/valid_interfaces.t
ncm-network/src/test/resources/output/ipaddrshow
ncm-network/src/test/resources/output/ipaddrshowrename
ncm-network/src/test/resources/rename.pan

* support device configuration files with a suffix
(like bond0_slave_1 (from kickstart with bonding or em1_4 from NPar interfaces)
* fix typos in schema wrt OVSBond
* support device renaming
* distinguish valid ifup/ifdown names from interfaces

ncm-network: support device name with suffix

---

ncm-modprobe/src/main/perl/modprobe.pm

More fallout from quattor/ccm#169.
Blocking for 18.6.

ncm-modprobe: Don't use placeholder CCM::Configuration module

---

ncm-metaconfig/src/main/metaconfig/nginx/location.tt
ncm-metaconfig/src/main/metaconfig/nginx/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/nginx/return.tt
ncm-metaconfig/src/main/metaconfig/nginx/server.tt
ncm-metaconfig/src/main/metaconfig/nginx/tests/profiles/config.pan
ncm-metaconfig/src/main/metaconfig/nginx/tests/regexps/config/base

To be used for eg redirects (http to https; root to default path)

ncm-metaconfig: nginx: support return

---

ncm-grub/src/main/perl/grub.pm
ncm-grub/src/test/perl/methods.t
ncm-grub/src/test/resources/md5password.pan

ncm-grub: escape interpretation of value of md5 password as a regex and add sensitive flag to file editor.
A regular expresion 'qr/^password $val$/' results in the interpretation of the contents of $val as a regular expression if it contains regex characters, which md5 passwords do. This properly escapes it. There should be no backwards incompatibility unless someone was relying on this bug, but I can't think of how that could be used.
We should not show diffs of grub.conf changes since it will expose encrypted password+salt in the logs, so I've added the sensitive flag. If someone was relying on the diff of the grub.conf being available in the logs, or via --noaction, there may be a regression, but this change is necessary so there's no unintended leaks of salt+hash.

ncm-grub: escape interpretation of value of md5 password as a regex and add sensitive flag to file editor.

---

ncm-network/src/main/perl/network.pm
ncm-network/src/test/perl/simple.t
ncm-network/src/test/resources/simple_nobroadcast.pan

Improves upon fix to #1305 
Also provides a path without network restart to remove any configured broadcast that are equal to the computed default (via `ipcalc --broadcast ipaddr netmask`)

ncm-network: allow default broadcast

---

ncm-spma/src/main/perl/spma/yum.pm
ncm-spma/src/test/perl/yum-distro-sync.t
ncm-spma/src/test/perl/yum-update-pkgs.t
ncm-spma/src/test/perl/yum-wanted.t

This prevents running full distro-sync when filter is in use; which might trigger updates of any number of packages and possible installations of dependencies.

ncm-spma: yum: distro-sync only filtered packages (when filter is defined)

---

ncm-nscd/src/main/pan/components/nscd/schema.pan
ncm-nscd/src/main/perl/nscd.pm
ncm-nscd/src/main/perl/nscd.pod

Support for these were added to nscd some time ago:
* services by the version shipped with EL6.
* netgroup by the version shipped with EL7.
The version of nscd is checked to determine support for each.

ncm-nscd: Add support for caching /etc/services and /etc/netgroup

---

ncm-metaconfig/src/main/metaconfig/nginx/nginx.tt
ncm-metaconfig/src/main/metaconfig/nginx/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/nginx/tests/profiles/config.pan

Required by some services. By default nginx restricts the POST header body size to a few kilobytes.

ncm-metaconfig: add nginx client_max_body_size option

---

ncm-ceph/src/main/pan/components/ceph/v2/schema-mds.pan

New for luminous: https://ceph.com/community/new-luminous-cephfs-metadata-server-memory-limits/

ncm-ceph: use mds cache memory limit instead of deprecated cache size

---

ncm-metaconfig/src/main/metaconfig/mailrc/element.tt
ncm-metaconfig/src/main/metaconfig/mailrc/main.tt
ncm-metaconfig/src/main/metaconfig/mailrc/pan/config.pan
ncm-metaconfig/src/main/metaconfig/mailrc/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/mailrc/tests/profiles/account_config.pan
ncm-metaconfig/src/main/metaconfig/mailrc/tests/profiles/config.pan
ncm-metaconfig/src/main/metaconfig/mailrc/tests/regexps/account_config
ncm-metaconfig/src/main/metaconfig/mailrc/tests/regexps/config/base
ncm-metaconfig/src/main/metaconfig/mailrc/tests/regexps/config/neg
ncm-metaconfig/src/test/perl/service-mailrc.t

This service allows you to configure mail.rc or .mailrc files
for an example see https://coderwall.com/p/ez1x2w/send-mail-like-a-boss

ncm-metaconfig: add mailrc service

---

ncm-systemd/src/main/perl/Systemd/Service/Unit.pm
ncm-systemd/src/test/perl/service-unit.t

This is needed if you need to configure units with systemd-escape'd values, which seems to be buggy on certain EL7 version (e.g. on centos 7.5)

ncm-systemd: handle systemd escaping bug

---

ncm-authconfig/src/main/perl/authconfig.pm

pod `=cut` needs a blank line before (and after). Otherwise this results in podlint errors and most of the code beeing generated as documentation.

ncm-authconfig: fix documentation

---

ncm-freeipa/src/main/perl/freeipa.pm

ncm-freeipa: docs - fix code blocks and correct method title

---

ncm-opennebula/src/main/perl/OpenNebula/Server.pm

newline before pod directive is required.

ncm-opennebula: fix malformed pod syntax

---

ncm-filecopy/src/main/pan/components/filecopy/schema.pan
ncm-filecopy/src/main/perl/filecopy.pm

Currently, if restarting a service fails, that marks the whole component
as failed, preventing other components which depend on filecopy from
running. In practice, that usually causes more damage than the restart
failure, so lower the severity of restart failures to warnings.
I considered making the behavior configurable, but I'm not sure if that
would worth the effort.
Comments are welcome.

ncm-filecopy: Make restart failures non-fatal

---

ncm-systemd/src/main/perl/Systemd/Service/Chkconfig.pm

```C<text->text>``` fails as the first `>` is interpreted as the end of the block. should be escaped as ```C<< text->text >>```.

ncm-systemd: documentation fix: make sure '>' is not interpreted.

---

ncm-openstack/src/main/perl/OpenStack/Service.pm

ncm-openstack: documentation fix code block not starting with newline

---

ncm-symlink/src/main/pan/components/symlink/config.pan
ncm-symlink/src/main/pan/components/symlink/schema.pan
ncm-symlink/src/main/perl/symlink.pod
ncm-symlink/src/test/resources/simple_links.pan

- Move schema documentation into the schema
- clean the pan code up to spring 2017 cleanup style

ncm-symlink: cleanup and documentation restructuring

---

ncm-metaconfig/src/main/metaconfig/keepalived/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/keepalived/tests/profiles/config.pan
ncm-metaconfig/src/main/metaconfig/keepalived/tests/regexps/config/base
ncm-metaconfig/src/main/metaconfig/keepalived/virtual_ipaddress.tt
ncm-metaconfig/src/main/metaconfig/keepalived/vrrp_instance.tt
ncm-metaconfig/src/main/metaconfig/keepalived/vrrp_script.tt

add keepalived support for unicast peers in schema en TT file.

ncm-metaconfig: keepalived - support unicast peers, virtual routes and interface tracking

---

ncm-metaconfig/src/main/metaconfig/zookeeper/pan/config.pan
ncm-metaconfig/src/main/metaconfig/zookeeper/tests/profiles/server_config.pan
ncm-metaconfig/src/main/metaconfig/zookeeper/tests/regexps/server_config/base
ncm-metaconfig/src/main/metaconfig/zookeeper/tests/regexps/server_config/values

zookeeper-server was something from the old cloudera repo

ncm-metaconfig: zookeeper-server was renamed to zookeeper

---

ncm-opennebula/src/main/perl/OpenNebula/Network.pm
ncm-opennebula/src/test/perl/aii_network_ar.t

This is a bit silly issue (not sure why we didn't find this issue before...) 
It was not possible to add several ARs or IPs to the same virtual network from the AII when the VM is instantiated. This should fix that problem.

ncm-opennebula: fix add several ip/ars to same vnet

---

ncm-cron/src/main/pan/components/cron/schema.pan

Otherwise this causes the last processed to take precedence.
Resolves #1228.

ncm-cron: Throw an error if multiple cron jobs are defined with the same name

---

ncm-sysconfig/src/main/perl/sysconfig.pm
ncm-sysconfig/src/test/perl/configure.t
ncm-sysconfig/src/test/resources/configure.pan

Fixes #1191.
If the user has already included quotes in the value, this is detected and worked around.

ncm-sysconfig: Automatically quote values containing whitespace

---

ncm-opennebula/src/main/pan/quattor/aii/opennebula/schema.pan
ncm-opennebula/src/main/resources/network_level1.tt
ncm-opennebula/src/main/resources/tests/profiles/vm.pan
ncm-opennebula/src/main/resources/tests/regexps/aii_vmtemplate/simple
ncm-opennebula/src/test/perl/rpcdata.pm
ncm-opennebula/src/test/resources/vm.pan

Include virtio network queues support in libvirt
Fix: #1371 
See also: https://docs.opennebula.org/5.6/deployment/open_cloud_host_setup/kvm_driver.html

ncm-opennebula: add virtio queues support

---

ncm-metaconfig/src/main/metaconfig/nginx/nginx.tt
ncm-metaconfig/src/main/metaconfig/nginx/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/nginx/proxy.tt
ncm-metaconfig/src/main/metaconfig/nginx/server.tt
ncm-metaconfig/src/main/metaconfig/nginx/ssl.tt
ncm-metaconfig/src/main/metaconfig/nginx/tests/profiles/basic_ssl.pan
ncm-metaconfig/src/main/metaconfig/nginx/tests/regexps/config/base

- added a bunch of settings to be able to better configure SSL on nginx.
- changed the ciphersuite options so it is possible to follow https://mozilla.github.io/server-side-tls/ssl-config-generator/
- changed the default of gzip to false. As I understand it, if misconfigured it leaves you open to BREACH.

ncm-metaconfig: nginx add more ssl configuration options

---

ncm-freeipa/src/main/perl/FreeIPA/Cert.pm
ncm-freeipa/src/main/perl/FreeIPA/Client.pm
ncm-freeipa/src/main/perl/FreeIPA/NSS.pm
ncm-freeipa/src/test/perl/freeipa-nss.t
ncm-freeipa/src/test/perl/ipa-cert.t
ncm-freeipa/src/test/perl/rpc_data/cert
ncm-freeipa/src/test/perl/rpc_data/client
ncm-freeipa/src/test/perl/rpc_data/nss

Fixes a bug where each component run requests a new certificate.
Adds local certificate expiration validation check to determine if a new certificate needs to be retrieved

ncm-freeipa: only request new certificate when local one is expired/will expire soon

---

ncm-metaconfig/src/main/metaconfig/xinetd/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/xinetd/tests/regexps/rsync/base
ncm-metaconfig/src/main/metaconfig/xinetd/tests/regexps/tftp/base
ncm-metaconfig/src/main/metaconfig/xinetd/tests/regexps/time-stream/base

port is a valid xinetd option according to `xinetd.conf(5)`.
Also remove default values for `cps` and `per_source`.

metaconfig: Update xinetd schema to include "port"

---

ncm-metaconfig/src/main/metaconfig/generic/multiline.tt
ncm-metaconfig/src/main/metaconfig/generic/pan/multiline.pan
ncm-metaconfig/src/main/metaconfig/generic/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/generic/pan/string.pan
ncm-metaconfig/src/main/metaconfig/generic/string.tt
ncm-metaconfig/src/main/metaconfig/generic/tests/profiles/multiline.pan
ncm-metaconfig/src/main/metaconfig/generic/tests/profiles/string.pan
ncm-metaconfig/src/main/metaconfig/generic/tests/regexps/multiline
ncm-metaconfig/src/main/metaconfig/generic/tests/regexps/string
ncm-metaconfig/src/test/perl/service-generic.t

support writing simple string literal and multine text with metaconfig
Requires #1387

ncm-metaconfig generic templates

---

ncm-metaconfig/src/main/pan/components/metaconfig/schema.pan

- When producing JSON, a list should also be accepted as
valid. Before the change, only JSON objects could be
used as content.
- This should remain fully backwards compatible

ncm-metaconfig: the content should not only be a dict

---

ncm-ssh/src/main/pan/components/ssh/schema.pan

Add a schema entry for ssh client config option HashKnownHosts
Increasingly important option for security to slow/reduce discovery of additional hosts where a set of compromised credentials may work
Optional so no backwards compatibility problems

ncm-ssh: add HashKnownHosts schema entry

---

ncm-openvpn/src/main/perl/openvpn.pm

Since EL7+ uses systemd, calling /etc/init.d scripts is no longer supported for service control. The generic command 'service' works on either sysvinit or systemd, so is backwards and forwards compatible.

ncm-openvpn: Modified to use generic "service" command rather than init.d script

---

ncm-symlink/src/main/pan/components/symlink/config.pan
ncm-symlink/src/main/pan/components/symlink/schema.pan

ncm-symlink: tweak default replace options
The "all" and "none" replace options are mutually exclusive. The prefix
syntax meant there was no way for site-config to set replace/all without
modifying this file to comment out the replace/none line in config.pan.
By moving the setting one level higher in the tree, replace/none will
only be set if site-config has not created the replace sub-tree.
ncm-symlink: update schema to use absolute_file_path type
Specifying a symlink name with a trailing slash leads to a runtime
error. Instead use the schema to catch and prevent these errors at
compile time.

ncm-symlink minor PAN template fixes

---

ncm-metaconfig/src/main/metaconfig/slurm/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/slurm/pan/topology.pan
ncm-metaconfig/src/main/metaconfig/slurm/topology.tt

Slurm features support for topologies in the network. This PR provides a schema for a hierarchical 
tree setup.

ncm-metaconfig: slurm topology schema and tt file

---

ncm-icinga/src/main/pan/components/icinga/schema.pan

notification can be disabled with 'n', but the options were missing in the schema.

ncm-icinga: add missing notification options

---

ncm-ssh/src/main/pan/components/ssh/schema.pan

Add schema entry and validation for RevokedKeys option
Adds the RevokedKeys option to allow the banning of ssh keys that have become compromised.
Optional so I don't expect backwards compatibility issues.
I don't think the error call in the validation will ever be reached - in testing is_absolute_file_path() threw the error, but I don't know if that matters.

ncm-ssh: Add schema entry for RevokedKeys option

---

ncm-systemd/src/main/pan/components/systemd/schema.pan
ncm-systemd/src/main/resources/regular/tests/profiles/unitfile.pan
ncm-systemd/src/main/resources/regular/tests/regexps/unitfile0/value
ncm-systemd/src/main/resources/unitfile/service.tt

This add a couple of sandboxing options that can be used in systemd unit from https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Sandboxing
I've only added the ones I need, but the list of potential options is long. Should I add all of them?

ncm-systemd: add extra unit options for sandboxing

---

ncm-altlogrotate/src/main/pan/components/altlogrotate/schema.pan

Some things run once a month or once a week and rotating too frequently takes away the purpose of a log file.

ncm-altlogrotate: allow yearly rotation

---

ncm-systemd/src/main/pan/components/systemd/config.pan
ncm-systemd/src/main/pan/components/systemd/schema.pan
ncm-systemd/src/main/resources/regular/tests/profiles/unitfile.pan
ncm-systemd/src/main/resources/regular/tests/regexps/unitfile0/value
ncm-systemd/src/main/resources/unitfile/service-socket.tt
ncm-systemd/src/main/resources/unitfile/service.tt
ncm-systemd/src/main/resources/unitfile/socket.tt

This add supports for a `[Socket]` section in a systemd unit.
It builds on top of and requires #1396 
Please have look @stdweird

ncm-systemd: Add support for Socket in units

---

ncm-download/src/test/resources/download.pan

Mostly just because I saw it and it annoyed me.

ncm-download: Fix white-space lint in test resources

---

ncm-metaconfig/src/main/metaconfig/udev/action_attr.tt
ncm-metaconfig/src/main/metaconfig/udev/pan/action_attr.pan
ncm-metaconfig/src/main/metaconfig/udev/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/udev/tests/profiles/action_attr.pan
ncm-metaconfig/src/main/metaconfig/udev/tests/regexps/action_attr/base

some basic structure to set attributes on (block)devices

ncm-metaconfig: udev: add more udev rules

---

ncm-metaconfig/src/main/metaconfig/httpd/pan/schema.pan

replaces: #1435 
requires: #1370

ncm-metaconfig: allow auth_type 'CAS' in httpd schema

---

ncm-metaconfig/src/main/metaconfig/mysql/pan/config.pan
ncm-metaconfig/src/main/metaconfig/mysql/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/mysql/tests/profiles/config.pan
ncm-metaconfig/src/main/metaconfig/mysql/tests/regexps/config/base
ncm-metaconfig/src/test/perl/service-mysql.t

I have realised that we are using mysql/mariadb metaconfig setups but our current schema is not available from upstream. We need to change the mysql conf to time to time for our cloud clusters for instance. 
Maybe this could be useful for someone else.

ncm-metaconfig: add mysql conf

---

ncm-ntpd/src/main/pan/components/ntpd/schema.pan
ncm-ntpd/src/main/perl/ntpd.pm
ncm-ntpd/src/test/perl/configure.t
ncm-ntpd/src/test/resources/interface.pan
ncm-ntpd/src/test/resources/regexps/interface

Supersedes #1437 which was messed up by trying to use the webUI to make minor edits.

ncm-ntpd: Add support for the 'interface' directive

---

.github/workflows/continuous-integration.yaml

For reason unknown to me, downloading maven dependencies can fail if you run it with github actions. First downloading all dependencies and then running the tests does seem to work consistently.
@ned21 this works (so far) all the time for me. The caching with github action doesn't seem to be 100% reliable. Sometimes it gets a hit, sometimes not.

gh action test: first download all maven dependencies

---

ncm-systemd/src/main/pan/components/systemd/schema.pan
ncm-systemd/src/main/resources/regular/tests/profiles/unitfile.pan
ncm-systemd/src/main/resources/regular/tests/regexps/unitfile0/value
ncm-systemd/src/main/resources/unitfile/service-socket.tt

This PR add support for the resource control options in systemd units.
Based on #1484.

ncm-systemd: add support for resource control in units

---

ncm-filecopy/src/main/perl/filecopy.pm
ncm-metaconfig/src/main/pan/components/metaconfig/schema.pan
ncm-metaconfig/src/main/perl/metaconfig.pm
ncm-metaconfig/src/test/perl/actions.t
ncm-metaconfig/src/test/perl/aii_command.t
ncm-metaconfig/src/test/perl/commands.t
ncm-metaconfig/src/test/perl/configure.t
ncm-metaconfig/src/test/resources/aii.pan
ncm-metaconfig/src/test/resources/commands.pan
ncm-metaconfig/src/test/resources/commands_fail_pre.pan
ncm-metaconfig/src/test/resources/simple_commands.pan

ncm-metaconfig: support running arbitrary commands in various steps

---

ncm-metaconfig/src/main/metaconfig/rsyslog/pan/actions.pan

The current template is not correct.

ncm-metaconfig: dynaFile (rsyslog) is a name of a template, not a path

---

ncm-systemd/src/main/perl/Systemd/Service.pm
ncm-systemd/src/main/perl/Systemd/Systemctl.pm
ncm-systemd/src/test/perl/service.t
ncm-systemd/src/test/perl/systemctl.t

If performing an action fails for one unit (e.g., because one tries to
enable a service which is not installed), then systemctl usually returns
a non-descriptive error like "No such file or directory", without any
indications for which unit caused the failure. What's worse, the rest of
the units will not be acted on either, often resulting in much more
breakage than the problematic unit would warrant.
To avoid this, perform actions one unit at a time.

ncm-systemd: Perform actions one unit at a time

---

ncm-opennebula/src/main/pan/components/opennebula/schema.pan
ncm-opennebula/src/main/pan/quattor/aii/opennebula/schema.pan
ncm-opennebula/src/main/perl/OpenNebula/Server.pm
ncm-opennebula/src/main/perl/opennebula.pm
ncm-opennebula/src/main/resources/oned_level1.tt
ncm-opennebula/src/main/resources/tests/profiles/vm.pan
ncm-opennebula/src/main/resources/tests/profiles/vmgroup.pan
ncm-opennebula/src/main/resources/tests/regexps/aii_vmtemplate/simple
ncm-opennebula/src/main/resources/tests/regexps/oned/oned_template
ncm-opennebula/src/main/resources/tests/regexps/vmgroup/simple
ncm-opennebula/src/main/resources/vmgroup.tt
ncm-opennebula/src/main/resources/vmtemplate.tt
ncm-opennebula/src/test/perl/rpcdata.pm
ncm-opennebula/src/test/perl/vmgroup.t
ncm-opennebula/src/test/resources/one.pan
ncm-opennebula/src/test/resources/vmgroup.pan

Fix: #1350 
**NOTE:** Requires #1378 and requires #1371 which should be reviewed/merged first
**NOTE:** It requires the new  Net::OpenNebula 0.316.0 or newer to work.
This PR is backwards compatible with previous ONE versions.
More info about VM groups:
https://docs.opennebula.org/5.8/advanced_components/application_flow_and_auto-scaling/vmgroups.html

ncm-opennebula: include OpenNebula 5.8.x and vmgroups support

---

ncm-opennebula/src/main/pan/components/opennebula/schema.pan
ncm-opennebula/src/main/pan/quattor/aii/opennebula/schema.pan
ncm-opennebula/src/main/perl/OpenNebula/Server.pm
ncm-opennebula/src/main/perl/opennebula.pm
ncm-opennebula/src/main/resources/imagetemplate.tt
ncm-opennebula/src/main/resources/oned_level1.tt
ncm-opennebula/src/main/resources/tests/profiles/datastore_rdm.pan
ncm-opennebula/src/main/resources/tests/profiles/vm.pan
ncm-opennebula/src/main/resources/tests/profiles/vmgroup.pan
ncm-opennebula/src/main/resources/tests/regexps/aii_imagetemplate/simple
ncm-opennebula/src/main/resources/tests/regexps/aii_vmtemplate/simple
ncm-opennebula/src/main/resources/tests/regexps/datastore_rdm/simple
ncm-opennebula/src/main/resources/tests/regexps/oned/oned_template
ncm-opennebula/src/main/resources/tests/regexps/vmgroup/simple
ncm-opennebula/src/main/resources/vmgroup.tt
ncm-opennebula/src/main/resources/vmtemplate.tt
ncm-opennebula/src/test/perl/rpcdata.pm
ncm-opennebula/src/test/perl/vmgroup.t
ncm-opennebula/src/test/resources/one.pan
ncm-opennebula/src/test/resources/vmgroup.pan

Fix: #1426 
**NOTE:** Requires #1391 which must be reviewed/merged first.
**NOTE:** It requires the new `Net::OpenNebula 0.316.0` or newer to work.
More info about RDM datastores and disks pt with libvirt:
https://docs.opennebula.org/5.8/deployment/open_cloud_storage_setup/dev_ds.html

ncm-opennebula: RDM datastore support

---

ncm-metaconfig/src/main/metaconfig/slurm/gres.tt
ncm-metaconfig/src/main/metaconfig/slurm/job_container.tt
ncm-metaconfig/src/main/metaconfig/slurm/pan/config.pan
ncm-metaconfig/src/main/metaconfig/slurm/pan/dbd.pan
ncm-metaconfig/src/main/metaconfig/slurm/pan/gres.pan
ncm-metaconfig/src/main/metaconfig/slurm/pan/job_container.pan
ncm-metaconfig/src/main/metaconfig/slurm/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/slurm/tests/profiles/config.pan
ncm-metaconfig/src/main/metaconfig/slurm/tests/profiles/gres.pan
ncm-metaconfig/src/main/metaconfig/slurm/tests/profiles/job_container.pan
ncm-metaconfig/src/main/metaconfig/slurm/tests/regexps/config/base
ncm-metaconfig/src/main/metaconfig/slurm/tests/regexps/gres/base
ncm-metaconfig/src/main/metaconfig/slurm/tests/regexps/job_container/base
ncm-metaconfig/src/main/metaconfig/slurm/type.tt
ncm-metaconfig/src/main/metaconfig/slurm/value.tt

This builds on top of #1422 and add/changes a couple of things so it works with slurm 20.11

ncm-metaconfig: add support for slurm 20.11

---

ncm-authconfig/src/main/pan/components/authconfig/sssd.pan

Fixes (harmless) error message in sssd logs

ncm-authconfig: sssd: remove unsupported force_timeout domain option

---

ncm-ceph/src/main/pan/components/ceph/config.pan

ncm-ceph: v1 no longer exists, switch to v2 as default

---

ncm-systemd/src/main/perl/Systemd/Service/Unit.pm
ncm-systemd/src/test/perl/service-unit.t
ncm-systemd/src/test/perl/service.t
ncm-systemd/src/test/resources/service-unit_simple_services.pan

Attempt to address issue #1395, but only if the RefuseManual* directives
are defined in the profiles. If those directives are coming from unit
fragments which are not managed by Quattor, then restart is still
attempted, and the component will fail.

ncm-systemd: Do not try to restart sevices which cannot

---

ncm-pam/src/main/pan/components/pam/config.pan

This fixes missing the dependency on spma and support for site-config.
As highlighted in quattor/ncm-ncd#130.

ncm-pam: Use component config header macro

---

ncm-resolver/src/main/pan/components/resolver/config.pan

This mainly just cleans up and adds support for site-config.

ncm-resolver: Use component config header macro

---

ncm-network/src/main/perl/network.pm

If open-vswitch is installed but not running, it prevents the network from being reconfigured:
[VERB] Getting output of command: /usr/bin/ovs-vsctl show
[ERROR] Error '/usr/bin/ovs-vsctl show' output: ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (No such file or directory)
The suggested change adds a check for the existence of the default database socket before running "ovs-vsctl show".
The only side effect I can imagine is that the change would also not gather the current Open vSwitch status if it's configured to use any database besides the default local socket.

ncm-network: check if ovs-vswitchd has been initialized to prevent failure

---

ncm-pam/src/main/pan/components/pam/schema.pan
ncm-resolver/src/main/pan/components/resolver/schema.pan

As a result of modernisation and refactoring work done to `ncm-resolver` and `ncm-pam`, the type definitions in the schema need renaming to match the standard format. e.g. `type component_resolver_type` should be `type resolver_component`.
The changes which caused this to be necessary were made in the following PRs, but the breakage was not noticeable at the time as macro expansion only happens during the release process (in this case for a release candidate) when the component templates are updated in the template library.
- quattor/configuration-modules-core#1511
- quattor/configuration-modules-core#1512
The schema should also not be bound to a path in the schema template, as this is inserted into `config.pan` by the macro.
See quattor/release#339.

Fix types for refactored components

---

ncm-chkconfig/src/main/pan/components/chkconfig/schema.pan

- With the migration to ncm-systemd, a configuration can define the legacy module and endup with an invalid
configuration if no service has been added to ncm-chkconfig

ncm-chkconfig: ensure that the services property doesn't remain undefined

---

ncm-metaconfig/src/main/pan/components/metaconfig/schema.pan

Current list of allowed service actions includes restart, reload, and stop_sleep_start.
This creates problems when the metaconfig component issues a reload action for a given service on a brand new host.
Since the host is new, that service has never been started, and therefore the reload command fails.
This also prevents the rest of Quattor components depending on metaconfig from running.
To solve this, allow service command condrestart, which works whether the service is already running or not.
Ensure the title of this pull-request starts with the component name followed by a colon, e.g.
> ncm-example: demonstrate what titles should look like
* What backwards incompatibility it …

ncm-metaconfig: Add service action condrestart

---

ncm-metaconfig/src/main/metaconfig/httpd/pan/schema.pan

This option enables certificate revocation list checking, as per the httpd docs: https://httpd.apache.org/docs/2.4/mod/mod_ssl.html#sslcarevocationcheck
The change is backwards compatiable, as `carevocationcheck` has been added as an optional.

ncm-metaconfig: httpd: Add carevocationcheck configuration option

---

ncm-metaconfig/src/main/metaconfig/slurm/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/slurm/tests/profiles/config.pan
ncm-metaconfig/src/main/metaconfig/slurm/tests/regexps/config/base
ncm-metaconfig/src/main/metaconfig/slurm/type.tt

@itkovian FYI, this is currently broken.

ncm-metaconfig: fix GresTypes in slurm config

---

ncm-metaconfig/src/main/metaconfig/beats/pan/schema_7.0.pan

This schema supports kafka output from a beat.

ncm-metaconfig: beat schema for 7.0+ with kafka output support

---

ncm-metaconfig/src/main/metaconfig/elasticsearch/pan/config_8.1.pan
ncm-metaconfig/src/main/metaconfig/elasticsearch/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/elasticsearch/pan/schema_8.1.pan
ncm-metaconfig/src/main/metaconfig/elasticsearch/tests/profiles/config_8.1.pan
ncm-metaconfig/src/main/metaconfig/elasticsearch/tests/regexps/config_8.1/base

ES removed part of the discovery schema in 8.x.

ncm-metaconfig: schema updates and tests for elasticsearch 8.1

---

ncm-modprobe/src/main/perl/modprobe.pm
ncm-modprobe/src/test/perl/configure.t
ncm-modprobe/src/test/perl/dracut.t

mkinitrd is dropped in RHEL9 - in previous OS releases mkinitrd was a wrapper that called dracut, with the options building an args string for dracut.  We only use a single option which is the same for mkinitrd and dracut, so it should be safe to replace mkinitrd references with dracut
Fixes #1577
Ensure the title of this pull-request starts with the component name followed by a colon, e.g.
> ncm-example: demonstrate what titles should look like

ncm-modprobe: Change mkinitrd references to dracut

---

ncm-network/src/main/perl/network.pm

update ethtool option mapping of gso, correct output seen from ethtool --show-offload DEVNAME is generic-segmentation-offload
setting gso in templates won't change this setting. 
see following in ncm log.
[INFO] running component: network
---------------------------------------------------------
[INFO] ethtool_set_iface_options: Skipping setting for eth2/offload/gso to off as not in ethtool
Not aware of any, checked output from ethtool -show-offload  DEVNAME on rhel7, 8 and 9.

ncm-network: fix gso hash mapping

---

ncm-systemd/src/main/pan/components/systemd/schema.pan
ncm-systemd/src/main/resources/regular/tests/profiles/unitfile.pan
ncm-systemd/src/main/resources/regular/tests/regexps/unitfile0/value
ncm-systemd/src/main/resources/unitfile/slice.tt

The resource control options are from the man page of rockylinux 8.6. It's mostly about cgroupvs2.

ncm-systemd: add support for slice and more resource control

---

.github/workflows/panlint.yaml
travis-build

workflows: Fully move travis-build into panlint

---

ncm-systemd/src/main/pan/components/systemd/schema.pan
ncm-systemd/src/main/resources/regular/tests/profiles/unitfile.pan
ncm-systemd/src/main/resources/regular/tests/regexps/unitfile0/value
ncm-systemd/src/main/resources/unitfile/path.tt

Adds support for [path] directives. This is useful for credential handling, where we can detect the template file changing and trigger a one-shot service.

ncm-systemd: Add path support

---

.github/workflows/continuous-integration.yaml

EL7 is too old of a default environment for us now, although we will still build nightlies on it as long as we have to support it.

workflows: Run unit tests on EL8

---

ncm-systemd/src/main/pan/components/systemd/schema.pan

ncm-systemd: All Exec* options can be lists of strings

---

.github/workflows/continuous-integration.yaml

Hopefully this fixes the intermediate failing of the tests.

tests: run go-offline in gh pipeline

---

ncm-autofs/src/main/pan/components/autofs/schema.pan

Leaving auto.master empty is fine if only amd-style maps, defined in
autofs.conf, are used. Add a bunch of amd-style options.

ncm-autofs: Schema updates

---

ncm-ntpd/src/main/pan/components/ntpd/schema.pan

The step value is represented in seconds.
See tinker definition in https://www.ntp.org/documentation/4.2.8-series/miscopt/

ncm-ntpd: fix type of ntpd_tinker_options/step #1600

---

ncm-ipmi/src/main/pan/components/ipmi/schema.pan
ncm-ipmi/src/main/perl/ipmi.pm
ncm-ipmi/src/test/perl/configure.t
ncm-ipmi/src/test/perl/pod-syntax.t
ncm-ipmi/src/test/resources/ipmi.pan

* Add more user account access control functionality including Privilege level
* Explicitly enable IPMI over LAN
* Uses existing variables and structure
* Remove the mandatory, but unused `net_interface` property

ncm-ipmi: Enhancements to IPMI module

---

ncm-metaconfig/src/main/metaconfig/generic/multiline_exact.tt
ncm-metaconfig/src/main/metaconfig/generic/pan/multiline_exact.pan
ncm-metaconfig/src/main/metaconfig/generic/tests/profiles/multiline_exact.pan
ncm-metaconfig/src/main/metaconfig/generic/tests/regexps/multiline_exact

ncm-metaconfig already adds a newline. A new multiline_exact was added instead of "fixing" multiline itself, so admins can migrate to the correct/exact format

ncm-metaconfig: generic: add multiline_exact module (avoids spurious newline)

---

ncm-ssh/src/main/pan/components/ssh/schema.pan

ncm-ssh: add option prohibit-password to PermitRootLogin parameter

---

ncm-dirperm/src/main/perl/dirperm.pm

What changed:
Variable in error display
Why it was necessary:
Simple typo fix. Replacing the "$user:$group" format $owner in the error display. This necessary because the current error message causes confusion with the format (user:group/group) 
Compatibility:
A string in the module logs, it does not break any dependency.

ncm-dirperm: fix the wrong variable which causes confusion on error display 

---

ncm-metaconfig/src/main/metaconfig/lvm_conf/main.tt
ncm-metaconfig/src/main/metaconfig/lvm_conf/pan/config.pan
ncm-metaconfig/src/main/metaconfig/lvm_conf/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/lvm_conf/tests/profiles/config.pan
ncm-metaconfig/src/main/metaconfig/lvm_conf/tests/regexps/config
ncm-metaconfig/src/test/perl/service-lvm.t

ability to set lvm configuration. Using lvmlocal.conf.
All default options supported taken from output lvmconfig --typeconfig default on rhel7 and 8.
Fixes #1566

ncm-metaconfig: add lvm_conf config support

---

ncm-metaconfig/src/main/metaconfig/zookeeper/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/zookeeper/server.tt
ncm-metaconfig/src/main/metaconfig/zookeeper/tests/profiles/server_config.pan
ncm-metaconfig/src/main/metaconfig/zookeeper/tests/regexps/server_config/values

ncm-metaconfig: zookeeper: fix 4lw options to a list of choice

---

ncm-spma/src/main/perl/spma/apt.pm
ncm-spma/src/main/resources/apt/source.tt
ncm-spma/src/main/resources/tests/profiles/apt-sources.pan
ncm-spma/src/main/resources/tests/regexps/apt-sources/standard
ncm-spma/src/main/resources/tests/regexps/apt-sources/trusted
ncm-spma/src/test/perl/apt-sources-generate.t

The existing code is not sufficient to manage apt-based hosts due to major bugs and missing functionality. This PR completes the implementation and can be used to fully manage hosts.

ncm-spma: apt: Finish implementation

---

ncm-metaconfig/src/main/metaconfig/beats/pan/schema_7.0.pan

For some reason this is a syntax error with choice.
As noted in quattor/release#344.

ncm-metaconfig: beats: Remove trailing comma in choice

---

ncm-metaconfig/src/main/metaconfig/udev/pan/rule.pan

It looks like these got nuked during a refactoring and rebase from 4949fda539a70dc56e5c7f6027b9b536a47b48d6 to ad09b9bbd92eadd777fc3fa36772f382ea390254.

ncm-metaconfig: udev: Restore missing bind and prefix

---

ncm-network/src/main/pan/components/network/config-nmstate.pan
ncm-network/src/main/perl/nmstate.pm

changes to nmstate.pm to address comments in previous pr.
- fixed typos and updated comments and docs to be more meaningful.
- commented out start_openvswitch, support for this will come later.
none

ncm-network: fix typos and updated comments

---

ncm-spma/pom.xml

As we are building the DEBs from the RPMs for now.
Pending an overhaul of how packages are built.

ncm-spma: Include APT backend in RPM for now

---

ncm-spma/src/main/perl/spma/yumdnf.pm

We don't support them anyway (the schema forces `/software/groups` to be empty).
Resolves #1524.

ncm-spma: yumdnf: Don't attempt to expand groups with repoquery

---

ncm-network/src/main/perl/nmstate.pm

improvements made to perl code to construct dummy interface hash. Suggested in previous pr review https://github.com/quattor/configuration-modules-core/pull/1614. 
no functional change.
Improve code.
none.

ncm-network: improvements made to perl code to construct dummy interface hash

---

ncm-network/src/main/pan/components/network/core-schema.pan

add missing gso for ethtool offload
add priority used in  nmstate.pm
to able to set gso for offload and priority values for configuring network manager policy rule.
*None

ncm-network: add two  missing schema types

---

ncm-altlogrotate/src/main/pan/components/altlogrotate/schema.pan
ncm-altlogrotate/src/main/perl/altlogrotate.pm
ncm-altlogrotate/src/test/perl/simple.t
ncm-altlogrotate/src/test/resources/simple.pan

This allows `logrotate` to rotate files as a specific user and group instead of the default (i.e. root).

ncm-altlogrotate: Support 'su' directive

---

ncm-network/src/main/pan/components/network/config-nmstate.pan

ncm-network: fix nmstate package definition in Kickstart config

---

ncm-network/src/main/perl/nmstate.pm

nmstate dossn't appear to handle route or rule commands. ignore any routes or rule which sets command with a warn.
Fixes #1627
see https://github.com/quattor/configuration-modules-core/issues/1627
when using Nmstate backend,  any routes and rules added with command will be ignored by Nmstate.

ncm-network: nmstate: handle command routes and rule cleanly

---

ncm-network/src/main/pan/components/network/core-schema.pan

This is the schema part of the fix for #1627.

ncm-network: Throw error if commands used with nmstate

---

ncm-network/src/main/perl/nmstate.pm

Set  mac-address for interface in nmstate config.
setting mac-address for interface when applying nmstate config.
None.

ncm-network: nmstate: add mac-address to nmstate config

---

ncm-nfs/src/main/pan/components/nfs/schema.pan
ncm-nfs/src/main/perl/nfs.pm
ncm-nfs/src/test/perl/configure.t
ncm-nfs/src/test/resources/configure_daemon.pan

The name of the service/daemon is OS dependent, default to the more modern name.
For example in EL6 it was `nfs`, in EL7 `nfs` was a symlink to `nfs-server`, in EL8 only `nfs-server` exists and in Ubuntu it is `nfs-kernel-server`.
Resolves #1618.

ncm-nfs: Allow daemon to reload to be specified

---

ncm-network/src/main/pan/components/network/core-schema.pan
ncm-network/src/test/perl/simple.t
ncm-network/src/test/resources/simple_shortrealhostname.pan

- Allow better support of software like Ceph where it is the recommended setting
This change is backward compatible but relaxes the requirements on `realhostname` property. I also checked the `template-library-standard`, `template-library-os`, `template_library_core` and `template-library-grid` repositories, as well as `configuration-modules-core`. `realhostname` is not referenced in any of them (except ncm-network schema definition in`template_library_core`) . Only `hostname` is set in `template-library-standard` but this property is not affected by this PR.

ncm-network core schema: allow realhostname to be a short hostname

---

ncm-metaconfig/src/main/metaconfig/slurm/pan/schema_23.02.pan
ncm-metaconfig/src/main/metaconfig/slurm/tests/profiles/cgroups.pan
ncm-metaconfig/src/main/metaconfig/slurm/tests/regexps/cgroups/base

There are a couple of stupid errors in it.

ncm-metaconfig: fix errors in slurm 23.02 schema

---

ncm-authconfig/src/main/pan/components/authconfig/sssd.pan

- Use `choice()` where possible.
- Use more specific types than just plain `long` and `string`.
Resolves #1471.

ncm-authconfig: sssd: Schema improvements

---

ncm-ssh/src/main/pan/components/ssh/schema.pan

add MaxSessions ssh option.
Allow setting of MaxSessions option for ssh
None.

ncm-ssh: add MaxSessions ssh option

---

ncm-network/src/main/pan/components/network/core-schema.pan
ncm-network/src/main/perl/nmstate.pm
ncm-network/src/test/perl/nmstate_simple.t

New approach to cleaning up inactive connections so have clean output after the run.
This also fixes an issue where active connnections named 'Wired connection ethX' are deleted before network changes are applied. This is means in some edge cases if first ncm-network run fails then you have no networking. Therefore no need to delete any auto connections created by NetworkManager, instead we just cleanup connections which are inactive at the end.
Wired connection ethX is created by NM automatically, to stop this one can install NetworkManage-config-server package, which stops NM creating such auto connections automaticailly.
provide option to turned this off.
to cleanup connections which have been made inactive after ncm run is completed with nmstate.
* What …

ncm-network: provide a better way to cleanup inactive connections

---

ncm-network/src/main/perl/nmstate.pm

add correct default_gateway for multihomed host
add creating of rt_tables when routing_tables is defined for policy based routing.
closes #1641
support for multihomed hosts and policy based routing
none.

ncm-network: nmstate - fix default gateway and policy routing table

---

ncm-network/src/main/perl/nmstate.pm
ncm-network/src/test/perl/nmstate_simple.t

- add profile name to make sure nmstateclt apply picks the right profile.
- explicitly set dhcp to false when setting static address. if there is an existing connection for same device with dhcp enabled nmstate wll not apply the change unless dhcp is explicitly is set to false.
closes #1636
To make sure right profile config is used by NM when nmstate applies the config.
None.

ncm-network: set profile-name and set dhcp to disable for static config

---

ncm-network/src/main/perl/network.pm
ncm-network/src/main/perl/nmstate.pm

two bug fixes for nmstate
fix to enable configuration for mutiple bonding interfaces. fixes #1638  
convert bonding option arp_ip_target to comma separated string. fixes #1639 
bug fix.
None.

ncm-network: fix multi bonding configuration and arp_ip_target bonding options

---

ncm-opennebula/src/main/pan/components/opennebula/common.pan
ncm-opennebula/src/main/pan/components/opennebula/schema.pan
ncm-opennebula/src/main/perl/OpenNebula/Ceph.pm
ncm-opennebula/src/main/resources/tests/profiles/datastore_cephsys.pan
ncm-opennebula/src/main/resources/tests/regexps/datastore_cephsys/simple
ncm-opennebula/src/test/perl/opennebula.t
ncm-opennebula/src/test/perl/rpcdata.pm
ncm-opennebula/src/test/resources/one.pan

This includes a new type of ceph datastore in opennebula. The ceph system datastore replaces the current shared system ds for live migrations. It should be the default one for ceph. 
* Fixes: #1649

ncm-opennebula: Add Ceph system datastore support

---

ncm-metaconfig/src/main/metaconfig/ssh/pan/schema.pan

I've found that our local schema differs from upstream with an extra option for SyslogFacility.

ncm-metaconfig: SSH add SyslogFacility option

---

ncm-metaconfig/src/main/pan/components/metaconfig/schema.pan

Fix a small but misleading typo in `ncm-metaconfig` schema

ncm-metaconfig: fix a typo in 'actions' resource description

---

ncm-network/src/main/perl/nmstate.pm
ncm-network/src/test/perl/nmstate_advance.t
ncm-network/src/test/perl/nmstate_simple.t
ncm-network/src/test/resources/nmstate_advance.pan

Fix for setting default gateway in nmstate with correct interface by looking up if gateway falls within subnet boundary.
next-hop-interface is mandatory for nmstate therefore figure out which interface subnet this gateway falls in. 
This will provide backward compatibility with network.pm
closes #1655 
to provide backward compatibility with network.pm when setting default gateway. without having to set gateway address on interface.
None.

ncm-network: nmstate dgw fix

---

ncm-systemd/src/main/perl/Systemd/Systemctl.pm

ncm-systemd: systemctl show can doublequoted backslash values

---

Dockerfile

This updates the dockerfile to be on sync with what we do in the github actions.
@aka7 build this with podman:
```
podman build -t quattor_test .
```
And then use it like:
```
podman run --user=$(id -ur):$(id -gr)  -it --userns=keep-id -v /path/to/configuration-modules-core:/quattor_test:z -e MVN_ARGS="-pl ncm-network" localhost/quattor_test
```
This runs the tests on your checkout.

tests: update dockerfile to rockylinux:8

---

ncm-metaconfig/src/main/metaconfig/httpd/config/global.tt
ncm-metaconfig/src/main/metaconfig/httpd/pan/schema.pan

- Needed to allow a basic remoteip config to be expressed for httpd, see https://httpd.apache.org/docs/2.4/mod/mod_remoteip.html.
- I have added the new definitions to the global section because, even though `RemoteIPProxyProtocol` can be defined at the vhost level, only one such definition will take affect, and do so globally.
None, the new features have been added as optional.

ncm-metaconfig: Allow basic httpd remoteip config to be expressed

---

ncm-metaconfig/src/main/metaconfig/beats/pan/schema_6.3.pan

**Why the change is necessary.**
To append the schema to support configuration `seccomp` default action. This is because in Rocky 9 filebeat may be presented to start See: [https://www.elastic.co/guide/en/beats/filebeat/6.8/linux-seccomp.html)](https://www.elastic.co/guide/en/beats/filebeat/6.8/linux-seccomp.html) 
resolves #1699 
**What backwards incompatibility it may introduce.**
The change has been tested on both Rocky 8 and Rocky 9 aquilon hosts with filebeat. This change allows filebeat to work on Rocky 9 while not showing negative effects for existing Rocky 8 hosts.
Services which configures filebeat.yml using this module should ensure that it continues to produce the correct configuration.

ncm-metaconfig beats: add seccomp to file beat schema to allow seccomp config for filebeat.yml

---

ncm-mysql/src/main/pan/components/mysql/schema.pan
ncm-mysql/src/main/perl/mysql.pm
ncm-mysql/src/main/perl/mysql.pod
ncm-mysql/src/test/resources/basic_service.pan

Add the possibility to store password in an encrypted way inside templates.
The schema is modified (`component_mysql_db_user` and `component_mysql_server_options` types) to add a boolean option `encrypted_adminpwd` which is false by default.
When `true`, the password has to be set in its encrypted form.
The easiest way to generate the encrypted password is the MySQL command `select password('plop');`
These modifications is fully backward compatible and could be use without changing anything in the templates.

ncm-mysql: add an option to use encrypted user password

---

ncm-grub/src/main/perl/grub.pm
ncm-grub/src/test/perl/methods.t

Ensure the title of this pull-request starts with the component name followed by a colon, e.g.
> ncm-example: demonstrate what titles should look like

Fixes #1704: ncm-grub::pxeboot return SUCCESS on non-UEFI systems

---

ncm-systemd/src/main/pan/components/systemd/schema.pan

Add a schema entry for PrivateNetwork to systemd 
(https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#PrivateNetwork=)
When deploying Rocky 9, I encounterd a problem where I needed to change this from its default setting, but was unable to as quattor did not know about this configuration option to systemd.

ncm-systemd: Add PrivateNetwork schema entry

---

ncm-spma/src/main/pan/components/spma/dnf/schema.pan

Support for spma/main_options in dnf backend, used by aii to configure tmp yum.conf during ks post.
So that we can set:
```pan
"/software/components/spma/main_options/best" = 1;
```
to be able to set `best=1` in aii yum.conf.
None. just schema update.
Resolves #1702.

ncm-spma: support for dnf backend schema to support main_options

---

ncm-ssh/src/main/pan/components/ssh/schema.pan

AllowTcpForwarding in ncm-ssh uses legacy_binary_affirmation_string, but other options such as "remote" and "local" are valid, so change schema to support valid values
Resolves #1690

ncm-ssh: extend AllowTcpForwarding to support valid values

---

ncm-sysctl/src/main/pan/components/sysctl/schema.pan
ncm-sysctl/src/test/perl/configure.t
ncm-sysctl/src/test/resources/simple.pan

* Trim newlines at EOF
* Remove shebang and editor config from tests
* Deprecate compat-v1 as having no effect 
(The code was removed pre-2008)

ncm-sysctl: Cleanup & fixes

---

ncm-metaconfig/src/main/metaconfig/beats/pan/schema_6.3.pan

This is a common mistake and is a syntax error.

ncm-metaconfig: Remove spurious semicolon at end of line

---

ncm-network/src/main/pan/components/network/core-schema-legacy.pan
ncm-network/src/main/pan/components/network/core-schema.pan
ncm-network/src/main/pan/components/network/types/network.pan
ncm-network/src/main/pan/components/network/types/network/backend/initscripts.pan
ncm-network/src/main/pan/components/network/types/network/backend/nmstate.pan
ncm-network/src/main/pan/components/network/types/network/route.pan
ncm-network/src/main/perl/nmstate.pm
ncm-network/src/test/perl/nmstate_simple.t
ncm-network/src/test/resources/nmstate_simple.pan

@aka7 as promised this splits out the nmstate specific parts of the schema into the new structure @stdweird designed.
This also defaults to using the new schema and to be honest I don't see a reason to keep the legacy schema file around.
Backwards incompatible from 23.6.0 for anyone setting `"nm_manage_dns" = true` or more generally for any sites using the current code from master.

ncm-network: Move nmstate options to new schema

---

ncm-spma/src/main/perl/spma/dnf.pm

exclude additional kernel packages part of the running kernel.
on rhel9, spma tries to remove kernel-module-core package even if version is the running kernel. This creates dependency package  kernel-core package to be removed by spma, and we get following error from dnf when spma runs:
```
Problem: The operation would result in removing the following protected packages: kernel-core
Nothing to do.
```
None.

ncm-spma: update to dnf backend to exclude additional kernel packages.

---

ncm-network/src/main/perl/nmstate.pm

ncm-nmstate: remove confusing warning in IPv6 configuration

---

.ci-scripts/panlint

This was mistakenly removed in 6818e3930b1f2c35ad402866aeaa93b67991a1e0

CI: panlint: Allow maven templates as first line

---

ncm-sudo/src/main/pan/components/sudo/schema.pan

This allows commands to be run in a pseudo-pty.
This is required by the CIS Benchmarks.

ncm-sudo: Add support for use_pty with sudoers

---

ncm-opennebula/src/main/pan/quattor/aii/opennebula/schema.pan
ncm-opennebula/src/main/resources/tests/profiles/vm.pan
ncm-opennebula/src/main/resources/vmtemplate.tt
ncm-opennebula/src/test/resources/vm.pan

Included cpuratio VM option for host overcommitment.
This change is backwards compatible
Resolves: #1736

ncm-opennebula: add cpu overcommit ratio option

---

ncm-authconfig/src/main/pan/components/authconfig/schema.pan
ncm-authconfig/src/main/pan/components/authconfig/sssd/ipa.pan
ncm-authconfig/src/main/pan/components/authconfig/sssd/ldap.pan
ncm-authconfig/src/main/pan/components/authconfig/sssd/tls.pan

This fixes some bugs in the previous regexps and removes a completely unused type.

ncm-authconfig: Use choice type where possible

---

ncm-spma/src/main/perl/spma/dnf.pm

bug fix to not remove packages listed in whitelist. In order to match, need to remove the epoch value which gets added in rpm earlier.
So that dnf backend will work with retaining packages listed in path "/software/components/spma/whitelist/"
none.

ncm-spma:  fix to retain rpms listed in whitelist path

---

ncm-opennebula/src/main/pan/quattor/aii/opennebula/schema.pan
ncm-opennebula/src/main/perl/OpenNebula/AII.pm
ncm-opennebula/src/main/resources/tests/profiles/vm.pan
ncm-opennebula/src/main/resources/tests/regexps/aii_vmtemplate/simple
ncm-opennebula/src/main/resources/tests/regexps/aii_vmtemplate/vm_template
ncm-opennebula/src/main/resources/vmtemplate.tt
ncm-opennebula/src/test/resources/vm.pan

Required to add q35 hw machine types
#1776 must be merged first 
Resolves:  #1821

ncm-opennebula: add libvirt hw machine type option

---

ncm-metaconfig/src/main/metaconfig/httpd/config/global.tt
ncm-metaconfig/src/main/metaconfig/httpd/pan/schema.pan

Why the change is necessary.
Needed to allow headers to be defined at the `httpd` global level.
What backwards incompatibility it may introduce.
None, the change should not affect those not seeking to define `httpd` headers at the global level.

ncm-metaconfig: Allow httpd wide headers to be set
