quattor/configuration-modules-core

ncm-ceph/src/main/perl/Ceph/commands.pm

ncm-ceph: fix git no ident error

---

ncm-spma/src/main/pan/components/spma/schema.pan

ncm-spma: Restrict repository name

---

ncm-nfs/src/main/pan/components/nfs/schema.pan
ncm-nfs/src/main/perl/nfs.pm
ncm-nfs/src/main/perl/nfs.pod

Fixes #452 as requested by @drossy

ncm-nfs: Support PanFS mounts

---

ncm-spma/src/main/pan/components/spma/schema.pan
ncm-spma/src/test/perl/repository_schema.t
ncm-spma/src/test/resources/quattor/schema.pan
ncm-spma/src/test/resources/repository_schema.pan

ncm-spma: allow '.' in repository names

---

ncm-mysql/src/main/pan/components/mysql/schema.pan

ncm-mysql: Schema fixes for `component_mysql_db_user` type

---

ncm-nrpe/src/main/perl/nrpe.pod

ncm-nrpe: Fix documentation issue

---

ncm-symlink/src/main/perl/symlink.pod

ncm-symlinks: documentation reformatting and clarification

---

ncm-metaconfig/src/main/pan/components/metaconfig/schema.pan

ncm-metaconfig: daemon user validation/deprecation should return true

---

ncm-metaconfig/src/main/metaconfig/elasticsearch/pan/config.pan
ncm-metaconfig/src/main/metaconfig/elasticsearch/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/elasticsearch/tests/profiles/config.pan
ncm-metaconfig/src/main/metaconfig/elasticsearch/tests/regexps/config/base
ncm-metaconfig/src/test/perl/service-elasticsearch.t

ncm-metaconfig: service elasticsearch

---

ncm-ssh/src/main/pan/components/ssh/schema.pan
ncm-ssh/src/main/perl/ssh.pm
ncm-ssh/src/test/perl/handle_files.t

* Add missing options to the schema.
* Fix lines that match partially the profile.

ncm-ssh: Fix small bugs

---

ncm-metaconfig/src/main/metaconfig/ncm-ncd/main.tt
ncm-metaconfig/src/main/metaconfig/ncm-ncd/pan/config.pan
ncm-metaconfig/src/main/metaconfig/ncm-ncd/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/ncm-ncd/tests/profiles/config.pan
ncm-metaconfig/src/main/metaconfig/ncm-ncd/tests/regexps/config/base
ncm-metaconfig/src/test/perl/service-ncm-ncd.t

see also https://github.com/quattor/ncm-ncd/pull/45

ncm-metaconfig: add service ncm-ncd

---

ncm-metaconfig/src/main/metaconfig/kibana/pan/config.pan
ncm-metaconfig/src/main/metaconfig/kibana/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/kibana/tests/profiles/config.pan
ncm-metaconfig/src/main/metaconfig/kibana/tests/regexps/config/base
ncm-metaconfig/src/test/perl/service-kibana.t

Adds support for kibana4 config (tested with 4.1.0 prerelease)

ncm-metaconfig: add kibana service

---

ncm-network/src/main/perl/network.pm
ncm-network/src/test/perl/simple.t
ncm-network/src/test/resources/simple.pan
ncm-network/src/test/resources/simple_base_profile.pan
ncm-network/src/test/resources/simple_realhostname.pan

ncm-network: Actually use realhostname if it has been provided

---

ncm-iptables/src/main/perl/iptables.pm

Hi,
We were reviewing the changes to ncm-iptables as we need to upgrade, and found usage of an insecure temporary file. Here's a PR to use a file created by File::Temp instead.

ncm-iptables: use secure temporary file from File::Temp

---

ncm-ceph/src/main/pan/components/ceph/schema-mds.pan
ncm-ceph/src/main/pan/components/ceph/schema-mon.pan
ncm-ceph/src/main/pan/components/ceph/schema-osd.pan
ncm-ceph/src/main/pan/components/ceph/schema-rgw.pan
ncm-ceph/src/main/pan/components/ceph/schema.pan

ncm-ceph: Extend schema with rgw options, and spread over multiple files

---

ncm-metaconfig/src/main/metaconfig/ganesha/2.2/attribute.tt
ncm-metaconfig/src/main/metaconfig/ganesha/2.2/tests/regexps/attribute/all
ncm-metaconfig/src/main/metaconfig/ganesha/2.2/tests/regexps/config2/export

Access_Type should be a string

ncm-metaconfig: ganesha: fix Access_Type type

---

ncm-network/src/main/perl/network.pm

ncm-network: handle uninitialised warning for aliases

---

ncm-ceph/src/main/pan/components/ceph/sudo.pan
ncm-ceph/src/main/perl/Ceph/daemon.pm

let file follow symlinks to check if empty

ncm-ceph: add -L to file

---

ncm-gpfs/src/main/perl/gpfs.pm

add gpfs.hadoop-connector to gpfs packages

ncm-gpfs: add gpfs.hadoop-connector to gpfs packages

---

ncm-opennebula/src/main/pan/components/opennebula/schema.pan
ncm-opennebula/src/main/perl/opennebula.pm

OpenNebula services are configured on demand. Most of the schema values are optional now:
* Fix #570 : Configure different OpenNebula services only if its required

ncm-opennebula: Configure Opennebula services on demand

---

ncm-autofs/src/test/perl/maps.t

Related to https://github.com/quattor/maven-tools/issues/67

ncm-autofs: maps unittest refine test

---

ncm-metaconfig/src/main/pan/components/metaconfig/schema.pan
ncm-metaconfig/src/main/perl/metaconfig.pm
ncm-metaconfig/src/main/perl/metaconfig.pod
ncm-metaconfig/src/test/perl/element.t
ncm-metaconfig/src/test/perl/tiny.t
ncm-metaconfig/src/test/resources/element.pan

ncm-metaconfig: support convert option for predefined conversions

---

ncm-metaconfig/src/main/metaconfig/beats/pan/filebeat.pan
ncm-metaconfig/src/main/metaconfig/beats/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/beats/pan/topbeat.pan
ncm-metaconfig/src/main/metaconfig/beats/tests/profiles/filebeat.pan
ncm-metaconfig/src/main/metaconfig/beats/tests/profiles/topbeat.pan
ncm-metaconfig/src/main/metaconfig/beats/tests/regexps/filebeat/base
ncm-metaconfig/src/main/metaconfig/beats/tests/regexps/topbeat/base
ncm-metaconfig/src/main/metaconfig/logstash/2.0/tests/profiles/server.pan
ncm-metaconfig/src/main/metaconfig/logstash/2.0/tests/regexps/server/base
ncm-metaconfig/src/main/metaconfig/logstash/config/input/beats.tt
ncm-metaconfig/src/main/metaconfig/logstash/pan/schema.pan
ncm-metaconfig/src/test/perl/service-beats.t

Support for [beats](https://www.elastic.co/products/beats) (and beats logstash input)

ncm-metaconfig: add service beats and logstash plugin

---

ncm-spma/src/main/pan/components/spma/yum/schema.pan
ncm-spma/src/main/perl/spma/yum.pm
ncm-spma/src/test/perl/yum-cleanup.t
ncm-spma/src/test/perl/yum-distro-sync.t
ncm-spma/src/test/perl/yum-expire-caches.t
ncm-spma/src/test/perl/yum-groups.t
ncm-spma/src/test/perl/yum-make-cache.t
ncm-spma/src/test/perl/yum-noaction.t
ncm-spma/src/test/perl/yum-spare-requires.t
ncm-spma/src/test/perl/yum-spare-whatreq.t
ncm-spma/src/test/perl/yum-transaction.t
ncm-spma/src/test/perl/yum-update-pkgs.t
ncm-spma/src/test/perl/yum-versionlock.t
ncm-spma/src/test/resources/noaction.pan

ncm-spma: add support for more yum.conf options

---

ncm-ceph/src/main/perl/Ceph/crushmap.pm
ncm-ceph/src/main/resources/tests/profiles/basic_crushmap.pan
ncm-ceph/src/main/resources/tests/regexps/basic_crushmap
ncm-ceph/src/test/perl/01-tt.t

ncm-ceph: add TT test

---

ncm-spma/src/main/perl/spma/yum.pm
ncm-spma/src/test/perl/yum-andreas.t
ncm-spma/src/test/perl/yum-distro-sync.t
ncm-spma/src/test/perl/yum-expire-caches.t
ncm-spma/src/test/perl/yum-groups.t
ncm-spma/src/test/perl/yum-make-cache.t
ncm-spma/src/test/perl/yum-spare-requires.t
ncm-spma/src/test/perl/yum-spare-whatreq.t
ncm-spma/src/test/perl/yum-transaction-size.t
ncm-spma/src/test/perl/yum-transaction.t
ncm-spma/src/test/perl/yum-update-pkgs-retry.t
ncm-spma/src/test/perl/yum-update-pkgs.t
ncm-spma/src/test/perl/yum-versionlock.t

ncm-spma: yum create and use cache

---

ncm-accounts/src/test/perl/profile_accounts.t
ncm-metaconfig/src/main/metaconfig/haproxy/defaults.tt
ncm-metaconfig/src/main/metaconfig/haproxy/global.tt
ncm-metaconfig/src/main/metaconfig/haproxy/hash_to_string.tt
ncm-metaconfig/src/main/metaconfig/haproxy/main.tt
ncm-metaconfig/src/main/metaconfig/haproxy/pan/config.pan
ncm-metaconfig/src/main/metaconfig/haproxy/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/haproxy/proxy.tt
ncm-metaconfig/src/main/metaconfig/haproxy/stats.tt
ncm-metaconfig/src/main/metaconfig/haproxy/tests/profiles/config.pan
ncm-metaconfig/src/main/metaconfig/haproxy/tests/regexps/config/base
ncm-metaconfig/src/test/perl/service-haproxy.t

Add a component for using metaconfig to configure haproxy

ncm-metaconfig: Add support for haproxy

---

ncm-metaconfig/src/main/metaconfig/zkrsync/main.tt
ncm-metaconfig/src/main/metaconfig/zkrsync/pan/config.pan
ncm-metaconfig/src/main/metaconfig/zkrsync/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/zkrsync/tests/profiles/testsession.pan
ncm-metaconfig/src/main/metaconfig/zkrsync/tests/regexps/testsession
ncm-metaconfig/src/main/metaconfig/zkrsync/value.tt
ncm-metaconfig/src/test/perl/service-zkrsync.t

config file for https://github.com/hpcugent/vsc-zk

ncm-metaconfig: add zkrsync config file 

---

ncm-iptables/ChangeLog
ncm-iptables/src/main/pan/components/iptables/config.pan
ncm-iptables/src/main/pan/components/iptables/schema.pan
ncm-iptables/src/main/perl/iptables.pm
ncm-iptables/src/test/perl/01-functions.t
ncm-iptables/src/test/perl/test-profiles.t
ncm-iptables/src/test/resources/basic.pan
ncm-iptables/src/test/resources/comment.pan

Fixes #576.
This includes a large amount of clean-up and re-factoring, because the source code made myself and others sad.
Review with [white-space changes hidden](https://github.com/quattor/configuration-modules-core/pull/688/files?w=1) for sanity.

ncm-iptables: Rewrite, add unit tests and add support for per-rule comments

---

ncm-network/src/main/perl/network.pm

ncm-network: support hardcoded ovirtmgmt bridge name

---

.gitignore

Add .idea/ directory from PyCharm IDE to .gitignore

Add PyCharm project files to .gitignore

---

ncm-spma/src/main/perl/spma-run

Depends on https://github.com/quattor/CAF/pull/173

ncm-spma: spma-run: Lock use reporter instance for reporting

---

ncm-accounts/src/main/perl/accounts.pod

ncm-accounts: make documentation a bit more consistent

---

ncm-autofs/pom.xml
ncm-autofs/src/main/perl/autofs.pod

- minor cleanup
- moved maintainter section to pom.xml

ncm-autofs: documentation fixes

---

ncm-amandaserver/src/main/perl/amandaserver.pod

various consistency, punctuation and spelling fixes.

ncm-amandaserver: documentation cleanup

---

ncm-altlogrotate/src/main/perl/altlogrotate.pod

ncm-altlogrotate: minor fixes for documentation

---

ncm-aiiserver/src/main/perl/aiiserver.pod

ncm-aiiserver: cleanup documentation

---

ncm-chkconfig/src/main/perl/chkconfig.pod

ncm-chkconfig: documentation cleanup

---

ncm-cups/src/main/perl/cups.pod

Documentation clean up and some minor structure fixes.

ncm-cups: cleanup documentation

---

ncm-directoryservices/src/main/perl/directoryservices.pod

ncm-directoryservices: clean up documentation

---

ncm-download/src/main/perl/download.pod

ncm-download: cleanup documentation

---

ncm-etcservices/src/main/perl/etcservices.pod

ncm-etcservices: documentation cleanup

---

ncm-fmonagent/pom.xml
ncm-fmonagent/src/main/perl/fmonagent.pod

- fixed developers
- removed superfluous content

ncm-fmonagent: documentation cleanup

---

ncm-modprobe/src/main/perl/modprobe.pm

RHEL6 uses initramfs in /boot/initramfs-* instead of initrd in
/boot/initrd-*. It provides a mkinitrd compatability wrapper which calls
dracut, but this module outputs them to the wrong place, leading to a
duplicate which isn't actually used.

ncm-modprobe: overwrite initramfs if it exists, instead of initrd.

---

ncm-metaconfig/src/main/metaconfig/xinetd/pan/services/rsync.pan
ncm-metaconfig/src/main/metaconfig/xinetd/tests/profiles/rsync.pan
ncm-metaconfig/src/main/metaconfig/xinetd/tests/regexps/rsync/base

add support for rsync in xinet.d and add some basic tests.

ncm-metaconfig: add rsync template for xinetd

---

ncm-ganglia/src/main/perl/ganglia.pod

ncm-ganglia: cleanup documentation

---

ncm-filesystems/src/main/perl/filesystems.pod

Mainly removed the TODO list. I will create github issues for them.

ncm-filesystems: documentation cleanup

---

ncm-gmond/src/main/perl/gmond.pod

ncm-gmond: clean up documentation

---

ncm-gmetad/src/main/perl/gmetad.pod

- removed dead link
- some style fixes
- fixed some typo's

ncm-gmetad: cleanup documentation

---

ncm-gpfs/src/main/perl/gpfs.pod

ncm-gpfs: clean up documentation

---

ncm-grub/pom.xml
ncm-grub/src/main/perl/grub.pod

- make sure all authors/developers are in pom.xml
- some clean up
- rework examples a little bit for clarity.

ncm-grub: clean up documentation

---

ncm-interactivelimits/src/main/perl/interactivelimits.pod

ncm-interactivelimits: clean up documentation

---

ncm-spma/src/main/perl/spma/yum.pm

ncm-spma: yum: pass error_is_warn from update_pkgs_retry also to spare_dependencies

---

ncm-ldconf/src/main/perl/ldconf.pod

ncm-ldconf: clean up documentation

---

ncm-hostsaccess/src/main/perl/hostsaccess.pod

* minor clean up.
* make sure example is recognised as code.

ncm-hostsaccess: clean up documentation

---

ncm-mcx/src/main/perl/mcx.pod

ncm-mcx: documentation clean up

---

ncm-ipmi/src/main/perl/ipmi.pod

ncm-ipmi: clean up documentation

---

ncm-metaconfig/src/main/perl/metaconfig.pod

ncm-metaconfig: clean up documentation

---

ncm-named/src/main/perl/named.pod

ncm-named: clean up documentation

---

ncm-nagios/src/main/perl/nagios.pod

- ensure paths are code blocks
- fix some minor spacing issues

ncm-nagios: documentation clean up

---

ncm-mysql/src/main/perl/mysql.pod

ncm-mysql: documentation clean up

---

ncm-modprobe/src/main/perl/modprobe.pod

ncm-modprobe: minor clean up documentation

---

ncm-nfs/src/main/perl/nfs.pod

ncm-nfs: clean up documentation

---

ncm-nrpe/src/main/perl/nrpe.pod

ncm-nrpe: documenatation clean up

---

ncm-nss/src/main/perl/nss.pod

ncm-nss: clean up documentation

---

ncm-ntpd/src/main/perl/ntpd.pod

- structure fixes
- make sure examples are code blocks
- various minor other fixes.

ncm-ntpd: documentation clean up

---

ncm-nscd/src/main/perl/nscd.pod

ncm-nscd: clean up documentation

---

ncm-nsca/src/main/perl/nsca.pod

- minor spelling corrections
- some fixes for consistency

ncm-nsca: clean up documentation

---

ncm-ofed/src/main/perl/ofed.pod

ncm-ofed: documentation cleanup

---

ncm-opennebula/src/main/perl/opennebula.pod

minor cleanup.
@alvarosimon I don't know if this will conflict with your work in https://github.com/quattor/configuration-modules-core/pull/890 . If so I'll rebase my work.

ncm-opennebula: clean up documentation

---

ncm-postfix/src/main/perl/postfix.pod

minor fixes for links and spacing.

ncm-postfix: clean up documentation

---

ncm-pnp4nagios/src/main/perl/pnp4nagios.pod

ncm-pnp4nagios: clean up documentation

---

ncm-pam/src/main/perl/pam.pod

ncm-pam: clean up documentation

---

ncm-openvpn/src/main/perl/openvpn.pod

ncm-openvpn: clean up documentation

---

ncm-sudo/src/main/perl/sudo.pod

- fix structure
- fix some typo's

ncm-sudo: clean up documentation

---

ncm-sysconfig/src/main/perl/sysconfig.pod

ncm-sysconfig: documentation clean up

---

ncm-sysctl/src/main/perl/sysctl.pod

ncm-sysctl: clean up documentation

---

ncm-syslog/src/main/perl/syslog.pod

ncm-syslog: documentation clean up

---

ncm-syslogng/src/main/perl/syslogng.pod

ncm-syslogng: clean up documentation

---

ncm-sendmail/src/main/perl/sendmail.pod

- some structural fixes for the lists
- removed some weird stuff at the end

ncm-sendmail: clean up documentation

---

ncm-puppet/src/main/perl/puppet.pod

- some consistency changes
- some minor spelling fixes

ncm-puppet: documentation clean up

---

ncm-profile/src/main/perl/profile.pod

some structure work and some spacing fixes.

ncm-profile: documentation clean up

---

ncm-postgresql/src/main/perl/postgresql.pod

ncm-postgresql: clean up documentation

---

ncm-ssh/src/main/perl/ssh.pod

ncm-ssh: documentation clean up

---

ncm-useraccess/src/main/perl/useraccess.pod

ncm-useraccess: clean up documentation

---

ncm-opennebula/src/main/pan/components/opennebula/schema.pan
ncm-opennebula/src/main/perl/opennebula.pm
ncm-opennebula/src/main/resources/datastore.tt
ncm-opennebula/src/main/resources/group.tt
ncm-opennebula/src/main/resources/tests/profiles/datastore_ceph.pan
ncm-opennebula/src/main/resources/tests/profiles/datastore_shar.pan
ncm-opennebula/src/main/resources/tests/profiles/group_one.pan
ncm-opennebula/src/main/resources/tests/profiles/user_one.pan
ncm-opennebula/src/main/resources/tests/profiles/user_oneadmin.pan
ncm-opennebula/src/main/resources/tests/profiles/vnet_br100.pan
ncm-opennebula/src/main/resources/tests/profiles/vnet_br101.pan
ncm-opennebula/src/main/resources/tests/profiles/vnet_ovsbr0.pan
ncm-opennebula/src/main/resources/tests/regexps/datastore_ceph/simple
ncm-opennebula/src/main/resources/tests/regexps/datastore_shar/share_template
ncm-opennebula/src/main/resources/tests/regexps/datastore_shar/simple
ncm-opennebula/src/main/resources/tests/regexps/vnet_br100/simple
ncm-opennebula/src/main/resources/tests/regexps/vnet_br101/simple
ncm-opennebula/src/main/resources/tests/regexps/vnet_ovsbr0/simple
ncm-opennebula/src/main/resources/user.tt
ncm-opennebula/src/main/resources/vnet.tt
ncm-opennebula/src/test/perl/rpcdata.pm
ncm-opennebula/src/test/resources/one.pan

This PR changes OpenNebula users/groups/vnets/datastores resources schema to use dictionaries
* Fix: #834 : Change some schema resource types to dictionaries instead lists

ncm-opennebula: Use resource dictionaries instead of lists

---

ncm-systemd/src/main/perl/Systemd/Service/Unit.pm

ncm-systemd: Fix links where they should not be used

---

ncm-opennebula/src/main/pan/components/opennebula/schema.pan
ncm-opennebula/src/main/perl/opennebula.pm
ncm-opennebula/src/main/perl/opennebula.pod
ncm-opennebula/src/main/resources/datastore.tt
ncm-opennebula/src/main/resources/group.tt
ncm-opennebula/src/main/resources/oneflow.tt
ncm-opennebula/src/main/resources/tests/profiles/datastore_ceph.pan
ncm-opennebula/src/main/resources/tests/profiles/datastore_shar.pan
ncm-opennebula/src/main/resources/tests/profiles/group_one.pan
ncm-opennebula/src/main/resources/tests/profiles/oneflow.pan
ncm-opennebula/src/main/resources/tests/profiles/user_one.pan
ncm-opennebula/src/main/resources/tests/profiles/user_oneadmin.pan
ncm-opennebula/src/main/resources/tests/profiles/vnet_br100.pan
ncm-opennebula/src/main/resources/tests/profiles/vnet_br101.pan
ncm-opennebula/src/main/resources/tests/profiles/vnet_ovsbr0.pan
ncm-opennebula/src/main/resources/tests/regexps/datastore_ceph/simple
ncm-opennebula/src/main/resources/tests/regexps/datastore_shar/share_template
ncm-opennebula/src/main/resources/tests/regexps/datastore_shar/simple
ncm-opennebula/src/main/resources/tests/regexps/oneflow/oneflow_template
ncm-opennebula/src/main/resources/tests/regexps/oneflow/simple
ncm-opennebula/src/main/resources/tests/regexps/vnet_br100/simple
ncm-opennebula/src/main/resources/tests/regexps/vnet_br101/simple
ncm-opennebula/src/main/resources/tests/regexps/vnet_ovsbr0/simple
ncm-opennebula/src/main/resources/user.tt
ncm-opennebula/src/main/resources/vnet.tt
ncm-opennebula/src/test/perl/opennebula.t
ncm-opennebula/src/test/perl/rpcdata.pm
ncm-opennebula/src/test/resources/one.pan
ncm-opennebula/src/test/resources/oneflow.pan

This PR includes OneFlow configuration support and unittest.
* Fix #755 : Include OneFlow support
**NOTE: This PR depends on #888 that should be reviewed/merged first**

ncm-opennebula: Include OneFlow support

---

ncm-opennebula/src/main/pan/components/opennebula/schema.pan
ncm-opennebula/src/main/perl/opennebula.pm
ncm-opennebula/src/main/perl/opennebula.pod
ncm-opennebula/src/main/resources/datastore.tt
ncm-opennebula/src/main/resources/group.tt
ncm-opennebula/src/main/resources/tests/profiles/datastore_ceph.pan
ncm-opennebula/src/main/resources/tests/profiles/datastore_shar.pan
ncm-opennebula/src/main/resources/tests/profiles/group_one.pan
ncm-opennebula/src/main/resources/tests/profiles/user_one.pan
ncm-opennebula/src/main/resources/tests/profiles/vnet_br100.pan
ncm-opennebula/src/main/resources/tests/profiles/vnet_br101.pan
ncm-opennebula/src/main/resources/tests/profiles/vnet_ovsbr0.pan
ncm-opennebula/src/main/resources/tests/regexps/datastore_ceph/simple
ncm-opennebula/src/main/resources/tests/regexps/datastore_shar/share_template
ncm-opennebula/src/main/resources/tests/regexps/datastore_shar/simple
ncm-opennebula/src/main/resources/tests/regexps/group_one/simple
ncm-opennebula/src/main/resources/tests/regexps/user_one/simple
ncm-opennebula/src/main/resources/tests/regexps/user_one/user_forbidden
ncm-opennebula/src/main/resources/tests/regexps/vnet_br100/simple
ncm-opennebula/src/main/resources/tests/regexps/vnet_br101/simple
ncm-opennebula/src/main/resources/tests/regexps/vnet_ovsbr0/simple
ncm-opennebula/src/main/resources/user.tt
ncm-opennebula/src/main/resources/vnet.tt
ncm-opennebula/src/test/perl/host.t
ncm-opennebula/src/test/perl/rpcdata.pm
ncm-opennebula/src/test/resources/one.pan

**NOTE:** This PR requires `Net-OpenNebula-0.309.0` to work
* Fix #959 : Include labels support
* Fix #966 : fix `Net::OpenNebula` `0.309.0`  host rpc_history

ncm-opennebula: Include OpenNebula labels support

---

ncm-download/src/main/perl/download.pm
ncm-download/src/test/perl/download.t

See issue #975 for discussion. Summary: downloads should be atomic by downloading to a temporary file and renaming. An unsuccessful/partial download could cause a problem for a process that tries to use it later or during the download even in the successful case.
.$filename.part files will be created in the target directory temporarily. This could potentially cause a problem for something which finds these files and reacts badly. It also means more disk is used temporarily during the download, if the file already exists.
Fixes #975.

ncm-download: download to temporary file.

---

ncm-accounts/src/main/perl/accounts.pod

Some minor fixes to for valid links.

ncm-accounts: Minor documentation fixes

---

ncm-shorewall/src/main/perl/shorewall.pod

ncm-shorewall: clean up documentation

---

ncm-filesystems/src/main/perl/filesystems.pm
ncm-gmetad/src/main/perl/gmetad.pm
ncm-gmond/src/main/perl/gmond.pm
ncm-interactivelimits/src/main/pan/components/interactivelimits/config.pan
ncm-interactivelimits/src/main/pan/components/interactivelimits/schema.pan
ncm-interactivelimits/src/main/perl/interactivelimits.pm
ncm-interactivelimits/src/test/perl/simple.t
ncm-interactivelimits/src/test/resources/simple.pan
ncm-libvirtd/src/main/perl/libvirtd.pm
ncm-nagios/src/main/perl/nagios.pm
ncm-nrpe/src/main/perl/nrpe.pm
ncm-nrpe/src/test/perl/configure.t
ncm-nsca/src/main/perl/nsca.pm
ncm-syslogng/src/main/perl/syslogng.pm
ncm-useraccess/src/main/perl/useraccess.pm

In preparation of https://github.com/quattor/CCM/issues/107
Fixes #973

Round of cleanup to prepare for removal of CCM::Property module

---

ncm-gpfs/src/main/pan/components/gpfs/schema.pan
ncm-gpfs/src/main/perl/gpfs.pm
ncm-gpfs/src/test/perl/base.t
ncm-gpfs/src/test/resources/base.pan

gpfs with ccr needs some more files.
Will add some test for this, already made PR for qmmpack

ncm-gpfs: add ccr support

---

.docbuilder.cfg

required for https://github.com/quattor/release/pull/277

add .docbuilder.cfg for documentation.

---

ncm-download/src/main/perl/download.pm

Replaces #925 
Requires https://github.com/quattor/CAF/pull/203

ncm-download: switch to CAF::Download::LWP

---

ncm-shorewall/src/main/pan/components/shorewall/schema.pan
ncm-shorewall/src/main/perl/shorewall.pm
ncm-shorewall/src/main/resources/line/stoppedrules.tt
ncm-shorewall/src/main/resources/stoppedrules.tt
ncm-shorewall/src/main/resources/tests/profiles/stoppedrules.pan
ncm-shorewall/src/main/resources/tests/regexps/stoppedrules

See http://shorewall.net/manpages/shorewall-stoppedrules.html

ncm-shorewall: add stoppedrules support

---

ncm-spma/src/main/pan/components/spma/yum/schema.pan
ncm-spma/src/main/pan/components/spma/yumng/schema.pan

This is the first step towards implementation of #950.

Deprecate group support in YUM backends

---

ncm-network/src/main/pan/components/network/core-schema.pan

Requires https://github.com/quattor/template-library-core/pull/151

ncm-network: core-schema: add additional checks to make sure gateway and broadcast are in network range

---

ncm-accounts/src/main/perl/accounts.pm
ncm-authconfig/src/main/perl/authconfig.pm

ncm-accounts/ncm-authconfig: handle sensitive data 

---

ncm-path/pom.xml
ncm-path/src/main/pan/components/path/config.pan
ncm-path/src/main/pan/components/path/schema.pan
ncm-path/src/main/perl/path.pm
ncm-path/src/test/perl/00-tqu.t
ncm-path/src/test/perl/simple.t
ncm-path/src/test/resources/simple.pan
pom.xml

ncm-path: add new component skeleton code

---

ncm-metaconfig/src/main/metaconfig/mlocate/pan/config.pan
ncm-metaconfig/src/main/metaconfig/mlocate/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/mlocate/tests/profiles/config.pan
ncm-metaconfig/src/main/metaconfig/mlocate/tests/regexps/config/base
ncm-metaconfig/src/main/metaconfig/mlocate/updatedb.tt
ncm-metaconfig/src/test/perl/service-mlocate.t

Add metaconfig files for mlocate/slocate/updatedb.

ncm-metaconfig: add mlocate

---

ncm-syslog/src/main/perl/syslog.pm
ncm-syslog/src/test/perl/configure.t
ncm-syslog/src/test/resources/basic.pan

Fixes issue reported in https://github.com/quattor/release/issues/301#issuecomment-320619630

ncm-syslog: escape certain special regexp characters

---

ncm-cups/src/main/perl/cups.pm

ncm-cups: fix compatibility with EL7

---

ncm-opennebula/src/main/pan/quattor/aii/opennebula/schema.pan
ncm-opennebula/src/main/resources/raw_level1.tt
ncm-opennebula/src/main/resources/tests/profiles/vm.pan
ncm-opennebula/src/main/resources/tests/regexps/aii_vmtemplate/vm_template
ncm-opennebula/src/main/resources/vmtemplate.tt
ncm-opennebula/src/test/perl/rpcdata.pm
ncm-opennebula/src/test/resources/vm.pan

Include memorybacking options to setup hugepages behaviour from VM guests
* Fix: #1057

ncm-opennebula: include hugepages options

---

ncm-metaconfig/src/main/metaconfig/rsyslog/action.tt
ncm-metaconfig/src/main/metaconfig/rsyslog/element.tt
ncm-metaconfig/src/main/metaconfig/rsyslog/elements.tt
ncm-metaconfig/src/main/metaconfig/rsyslog/input.tt
ncm-metaconfig/src/main/metaconfig/rsyslog/inputs.tt
ncm-metaconfig/src/main/metaconfig/rsyslog/legacy/element.tt
ncm-metaconfig/src/main/metaconfig/rsyslog/main.tt
ncm-metaconfig/src/main/metaconfig/rsyslog/modules.tt
ncm-metaconfig/src/main/metaconfig/rsyslog/pan/actions.pan
ncm-metaconfig/src/main/metaconfig/rsyslog/pan/config.pan
ncm-metaconfig/src/main/metaconfig/rsyslog/pan/inputs.pan
ncm-metaconfig/src/main/metaconfig/rsyslog/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/rsyslog/prifile.tt
ncm-metaconfig/src/main/metaconfig/rsyslog/ruleset.tt
ncm-metaconfig/src/main/metaconfig/rsyslog/stop.tt
ncm-metaconfig/src/main/metaconfig/rsyslog/templates.tt
ncm-metaconfig/src/main/metaconfig/rsyslog/tests/profiles/config.pan
ncm-metaconfig/src/main/metaconfig/rsyslog/tests/regexps/config/base
ncm-metaconfig/src/test/perl/service-rsyslog.t

ncm-metaconfig: add support for rsyslog.conf file in rainerscript (http://www.rsyslog.com/doc/v8-stable/rainerscript/index.html)

ncm-metaconfig: rsyslog: rainer script configuration

---

ncm-ceph/src/main/pan/components/ceph/schema-mds.pan

http://docs.ceph.com/docs/master/cephfs/mds-config-ref/
mds log max segments
mds log max expiring

ncm-ceph: add mds options for log trimming

---

ncm-metaconfig/src/main/pan/components/metaconfig/schema.pan
ncm-metaconfig/src/main/perl/metaconfig.pm
ncm-metaconfig/src/test/perl/element.t
ncm-metaconfig/src/test/resources/element.pan

Requires https://github.com/quattor/CCM/pull/179

ncm-metaconfig: support new key conversion options from CCM::TextRender

---

ncm-systemd/src/main/pan/components/systemd/schema.pan

ncm-systemd: add support for AmbientCapabilities and CapabilityBoundingSet

---

ncm-ofed/src/main/perl/ofed.pm

ncm-ofed: import CAF::Service and enable NoActionSupported

---

ncm-cups/src/main/perl/cups.pm

I believe this finally resolves #1189 from @Pansanel.

ncm-cups: Stop daemon if server not enabled

---

ncm-opennebula/src/main/pan/quattor/aii/opennebula/schema.pan

Include support for VXLAN interfaces
* Fix: #1238

ncm-opennebula: fix aii vxlan interfaces

---

ncm-metaconfig/src/main/metaconfig/nginx/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/nginx/proxy.tt
ncm-metaconfig/src/main/metaconfig/nginx/tests/profiles/location.pan
ncm-metaconfig/src/main/metaconfig/nginx/tests/regexps/config/base

* Fix #1293  add extra options into nginx proxy location section

ncm-metaconfig: add more nginx proxy options

---

ncm-metaconfig/src/main/metaconfig/httpd/2.4/tests/profiles/oidc.pan
ncm-metaconfig/src/main/metaconfig/httpd/2.4/tests/regexps/oidc/base
ncm-metaconfig/src/main/metaconfig/httpd/config/gssapi.tt
ncm-metaconfig/src/main/metaconfig/httpd/config/oidc.tt
ncm-metaconfig/src/main/metaconfig/httpd/config/vhost.tt
ncm-metaconfig/src/main/metaconfig/httpd/pan/schema.pan

ncm-metaconfig: httpd: add openid connect configuration

---

ncm-network/src/main/perl/network.pm

ncm-network: no error wrt missing (IPv4) ip and netmask in a pure IPv6 config

---

ncm-metaconfig/src/main/metaconfig/ganesha/2.2/main.tt
ncm-metaconfig/src/main/metaconfig/ganesha/2.2/tests/profiles/config2.pan
ncm-metaconfig/src/main/metaconfig/ganesha/2.2/tests/regexps/config2/export
ncm-metaconfig/src/main/metaconfig/ganesha/pan/schema_v2.pan

Add Ganesha v2 `%include`   option
* Fix #1276

ncm-metaconfig: ganeshav2 add include

---

ncm-metaconfig/Dockerfile

metaconfig: Add dockerfile for running tests

---

ncm-gpfs/src/main/pan/components/gpfs/schema.pan
ncm-gpfs/src/main/perl/gpfs.pm

for gpfs 5, rpms of nfs-ganesha from CES are renamed, so should be recognized by component

ncm-gpfs: rpms nfs-ganesha renamed

---

ncm-metaconfig/src/main/metaconfig/libvirtd/guests.tt
ncm-metaconfig/src/main/metaconfig/libvirtd/pan/guests.pan
ncm-metaconfig/src/main/metaconfig/libvirtd/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/libvirtd/tests/profiles/guests.pan
ncm-metaconfig/src/main/metaconfig/libvirtd/tests/regexps/guests/base

* Fix #1287 : add libvirtd libvirt-guests configuration

ncm-metaconfig: add libvirt guests setup

---

ncm-filecopy/src/main/pan/components/filecopy/schema.pan
ncm-filecopy/src/main/perl/filecopy.pod

ncm-filecopy: Documentation: fix title level inconsistency 

---

ncm-ceph/src/main/perl/Ceph/OSDserver.pm
ncm-ceph/src/test/perl/configure.t
ncm-ceph/src/test/perl/osdserver-deploy.t
ncm-ceph/src/test/resources/tosdserver.pan

adds an extra check before trying to run ceph-volume create

ncm-ceph: test blkid of device before trying to deploy

---

ncm-metaconfig/src/main/metaconfig/irods/pan/access_control.pan
ncm-metaconfig/src/main/metaconfig/irods/pan/config.pan
ncm-metaconfig/src/main/metaconfig/irods/pan/hosts.pan
ncm-metaconfig/src/main/metaconfig/irods/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/irods/pan/server_config.pan
ncm-metaconfig/src/main/metaconfig/irods/tests/profiles/access_control.pan
ncm-metaconfig/src/main/metaconfig/irods/tests/profiles/config.pan
ncm-metaconfig/src/main/metaconfig/irods/tests/profiles/hosts.pan
ncm-metaconfig/src/main/metaconfig/irods/tests/profiles/server_config.pan
ncm-metaconfig/src/main/metaconfig/irods/tests/regexps/access_control
ncm-metaconfig/src/main/metaconfig/irods/tests/regexps/config/base
ncm-metaconfig/src/main/metaconfig/irods/tests/regexps/hosts
ncm-metaconfig/src/main/metaconfig/irods/tests/regexps/server_config
ncm-metaconfig/src/main/perl/metaconfig.pm
ncm-metaconfig/src/test/perl/service-irods.t

Requires quattor/CAF#265
Requires quattor/CCM#186

 ncm-metaconfig: add irods config files

---

ncm-spma/src/main/pan/components/spma/yum/schema.pan
ncm-spma/src/main/perl/spma/yum.pm
ncm-spma/src/test/perl/yum-cleanup-repos.t
ncm-spma/src/test/perl/yum-configure.t
ncm-spma/src/test/perl/yum-noaction.t

yum plugin in spmalight usage (or any usage of filters) should cleanup repositories, as this is not true userpkgs behaviour.

ncm-spma: yum: spmalight should cleanup repositories

---

ncm-openstack/src/main/pan/components/openstack/common.pan
ncm-openstack/src/main/pan/components/openstack/compute/nova.pan
ncm-openstack/src/main/pan/components/openstack/dashboard/horizon.pan
ncm-openstack/src/main/pan/components/openstack/identity/keystone.pan
ncm-openstack/src/main/pan/components/openstack/network/neutron.pan
ncm-openstack/src/main/perl/OpenStack/Nova.pm
ncm-openstack/src/main/resources/tests/profiles/neutron.pan
ncm-openstack/src/main/resources/tests/profiles/neutron_l3.pan
ncm-openstack/src/main/resources/tests/profiles/neutron_openvswitch.pan
ncm-openstack/src/main/resources/tests/regexps/neutron/neutron_template
ncm-openstack/src/main/resources/tests/regexps/neutron_l3/neutron_l3_template
ncm-openstack/src/main/resources/tests/regexps/neutron_l3/simple
ncm-openstack/src/test/perl/openstack.t
ncm-openstack/src/test/resources/os_resources.pan

**NOTE:** this PR requires https://github.com/quattor/CCM/pull/193
* Fix: #1353

ncm-openstack: set nova cpu/mem overcommit and add new hyps

---

ncm-metaconfig/src/main/metaconfig/rsyslog/pan/actions.pan

ncm-metaconfig: rsyslog: Tighten up schema and use choice for options

---

ncm-metaconfig/src/main/metaconfig/kafka/pan/config.pan
ncm-metaconfig/src/main/metaconfig/kafka/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/kafka/tests/profiles/config.pan
ncm-metaconfig/src/main/metaconfig/kafka/tests/regexps/config/base

- schema and config for Kafka, version 2.3.x
- tests

ncm-metaconfig: kafka 2.3.x

---

ncm-network/src/main/pan/components/network/core-schema.pan
ncm-network/src/main/perl/network.pm
ncm-network/src/test/perl/route_rule.t
ncm-network/src/test/perl/simple.t
ncm-network/src/test/resources/route_rule.pan

ncm-network: support rules and routes using routing tables

---

ncm-metaconfig/src/main/metaconfig/devicemapper/pan/schema.pan

current type does not make sense

ncm-metaconfig: devicemapper: fix bug in schema

---

ncm-network/src/main/pan/components/network/core-schema.pan
ncm-network/src/main/perl/network.pm
ncm-network/src/test/perl/route_rule.t
ncm-network/src/test/perl/simple.t
ncm-network/src/test/resources/route_rule.pan
ncm-network/src/test/resources/simple.pan
ncm-network/src/test/resources/simple_ethtool.pan
ncm-network/src/test/resources/simple_noethtool.pan

ncm-network: support ethtool channels

---

ncm-puppet/src/main/pan/components/puppet/schema.pan

Also document workaround.
Resolves #1416.

ncm-puppet: Document string quoting behaviour

---

.github/workflows/continuous-integration.yaml
Dockerfile
README.md

Setup a GitHub action to run the unit tests in a Docker container on every pull request to master.
I have not yet worked out how to make this Action running successfully a pre-merge status check but hopefully it will be obvious once it is merged.

Run Unit Tests in Docker using a GitHub action

---

ncm-metaconfig/src/main/metaconfig/singularity/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/singularity/singularity.tt

ncm-metaconfig: singularity - add limit_container_groups

---

ncm-cron/src/main/pan/components/cron/schema.pan

ncm-cron: Provide schema validation to match the component code

---

ncm-authconfig/src/main/pan/components/authconfig/sssd.pan

add schema option for sssd.conf

ncm-authconfig: sssd: add override_shell option

---

ncm-network/src/main/perl/network.pm
ncm-network/src/test/perl/valid_interfaces.t

ncm-network: cleanup network interfaces with partition info in the name

---

ncm-download/src/main/pan/components/download/schema.pan
ncm-download/src/main/perl/download.pm
ncm-download/src/test/perl/download.t
ncm-download/src/test/resources/download.pan

Requires https://github.com/quattor/template-library-core/pull/201

ncm-download: support daemon actions on change

---

ncm-shorewall/src/main/pan/components/shorewall/schema.pan
ncm-shorewall/src/main/perl/shorewall.pm
ncm-shorewall/src/main/resources/line/snat.tt
ncm-shorewall/src/main/resources/snat.tt
ncm-shorewall/src/main/resources/tests/profiles/snat.pan
ncm-shorewall/src/main/resources/tests/regexps/snat
ncm-shorewall/src/test/perl/configure.t
ncm-shorewall/src/test/resources/basic.pan

ncm-shorewall: add support for snat and deprecate masq

---

ncm-metaconfig/src/main/metaconfig/rsyslog/pan/actions.pan
ncm-metaconfig/src/main/metaconfig/rsyslog/pan/inputs.pan
ncm-metaconfig/src/main/metaconfig/rsyslog/pan/schema.pan

Support actions that output to Kafka.

ncm-metaconfig: rsyslog kafka output action

---

ncm-metaconfig/src/main/metaconfig/logstash/5.0/config/output/elasticsearch.tt
ncm-metaconfig/src/main/metaconfig/logstash/7.0/config/filter/json.tt
ncm-metaconfig/src/main/metaconfig/logstash/7.0/config/output/elasticsearch.tt
ncm-metaconfig/src/main/metaconfig/logstash/7.0/tests/profiles/config.pan
ncm-metaconfig/src/main/metaconfig/logstash/7.0/tests/regexps/config/base
ncm-metaconfig/src/main/metaconfig/logstash/pan/schema_7.0.pan

Add support for using a json filter in the logstash config

ncm-metaconfig: logstash 7.0 json filter

---

ncm-metaconfig/src/main/metaconfig/httpd/config/vhost.tt
ncm-metaconfig/src/main/metaconfig/httpd/pan/schema.pan

ncm-metaconfig: httpd - add h2 options

---

ncm-metaconfig/src/main/metaconfig/haproxy/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/haproxy/tests/profiles/config.pan
ncm-metaconfig/src/main/metaconfig/haproxy/tests/regexps/config/base

ncm-metaconfig: haproxy - add TLS ALPN extension options

---

ncm-metaconfig/src/main/metaconfig/mailrc/pan/schema.pan

ncm-metaconfig: mailrc - add missing ssl-verify option

---

ncm-metaconfig/src/main/metaconfig/nginx/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/nginx/ssl.tt
ncm-metaconfig/src/main/metaconfig/nginx/tests/regexps/config/base

ncm-metaconfig: nginx - add TLSv1.3 and dhparam options

---

ncm-metaconfig/src/main/metaconfig/haproxy/pan/schema.pan

ncm-metaconfig: haproxy add ssl-dh-param-file option

---

ncm-metaconfig/src/main/metaconfig/logstash/7.0/config/filter/geoip.tt
ncm-metaconfig/src/main/metaconfig/logstash/7.0/config/filter/grok.tt
ncm-metaconfig/src/main/metaconfig/logstash/7.0/config/filter/kv.tt
ncm-metaconfig/src/main/metaconfig/logstash/7.0/config/filter/mutate.tt
ncm-metaconfig/src/main/metaconfig/logstash/7.0/config/output/elasticsearch.tt
ncm-metaconfig/src/main/metaconfig/logstash/7.0/tests/profiles/config.pan
ncm-metaconfig/src/main/metaconfig/logstash/7.0/tests/profiles/server.pan
ncm-metaconfig/src/main/metaconfig/logstash/7.0/tests/regexps/server/base
ncm-metaconfig/src/main/metaconfig/logstash/pan/config_7.0.pan
ncm-metaconfig/src/main/metaconfig/logstash/pan/schema_7.0.pan
ncm-metaconfig/src/test/perl/service-logstash.t

- add geoip filter for logstash
- fix option names for kv filter
- try to get the tests for logstash/7.0 to run...

ncm-metaconfig: add geoip filter for logstash + fix tests

---

ncm-resolver/src/main/pan/components/resolver/schema.pan
ncm-resolver/src/main/perl/resolver.pm

Add support for writing options to resolv.conf. Also modernise the code.
THIS SOFTWARE IS CONTRIBUTED SUBJECT TO THE TERMS OF THE APACHE LICENSE, V.2.0. YOU MAY OBTAIN A COPY OF THE LICENSE AT https://www.apache.org/licenses/LICENSE-2.0.
THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) …

ncm-resolver: add support for options in resolv.conf

---

ncm-metaconfig/src/main/metaconfig/ganesha/2.2/attribute.tt
ncm-metaconfig/src/main/metaconfig/ganesha/2.2/tests/regexps/attribute/all
ncm-metaconfig/src/main/metaconfig/ganesha/2.2/tests/regexps/config2/export

This is mainly for gpfs CES that does not like this

ncm-metaconfig: ganesha: Access_Type should be enum, not string

---

.github/workflows/continuous-integration.yaml

For some reason, hashlib function does no longer work in the post step.
I've changed it to generate the hash in the beginning and store it in a
variable.

CI: fix hash key for m2 cache

---

ncm-metaconfig/src/main/metaconfig/jaas/jaas.tt
ncm-metaconfig/src/main/metaconfig/jaas/pan/schema.pan

Java Authentication and Authorization Service (JAAS).

ncm-metaconfig: jaas configuration file support

---

.github/workflows/continuous-integration.yaml
.github/workflows/panlint.yaml

There are deprecation warnings in the github actions runs.

avoid warnings in github action run

---

ncm-spma/src/main/perl/spma/dnf.pm

Fix bug in dnf provider to correctly exclude removal of packages core to running kernel so it doesn't try to remove running kernel.
Fixes #1565
The code to exclude the running kernel doesn't take into account the epoch value that is added in the $will_remove var. (i.e kernel-core-0: vs kernel-core. 0 is the epoch value, 0 is when no epoch value is set).  To fix this, I've now moved to do this within the existing loop which does removal for whitelist exclusion. 
see issue #1565
Tested on a rhel8 host which is using the dnf provider.

ncm-spma: fix dnf provider not to remove running kernel

---

ncm-cron/src/main/perl/cron.pm

ncm-cron: Use numeric comparison operator

---

ncm-metaconfig/src/main/metaconfig/hnormalise/pan/config.pan
ncm-metaconfig/src/main/metaconfig/hnormalise/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/hnormalise/tests/profiles/config.pan
ncm-metaconfig/src/main/metaconfig/hnormalise/tests/regexps/config/base
ncm-metaconfig/src/main/metaconfig/kafka/tests/profiles/config.pan
ncm-metaconfig/src/main/metaconfig/kafka/tests/regexps/config/base
ncm-metaconfig/src/test/perl/service-hnormalise.t
ncm-metaconfig/src/test/perl/service-kafka.t

kafka & hnormalise: Add and fix tests

---

ncm-shorewall/src/main/pan/components/shorewall/schema.pan

See https://shorewall.org/Docker.html

ncm-shorewall: add docker support

---

.github/workflows/continuous-integration.yaml
.github/workflows/panlint.yaml
Dockerfile

fix tests: add procps-ng for sysctl

---

ncm-metaconfig/src/main/metaconfig/slurm/pan/schema.pan
ncm-metaconfig/src/main/metaconfig/slurm/pan/schema_24.05.pan
ncm-metaconfig/src/main/metaconfig/slurm/tests/profiles/cgroups.pan
ncm-metaconfig/src/main/metaconfig/slurm/tests/profiles/config.pan
ncm-metaconfig/src/main/metaconfig/slurm/tests/profiles/dbd.pan
ncm-metaconfig/src/main/metaconfig/slurm/tests/regexps/cgroups/base
ncm-metaconfig/src/main/metaconfig/slurm/tests/regexps/config/base
ncm-metaconfig/src/main/metaconfig/slurm/tests/regexps/dbd/base
ncm-metaconfig/src/main/metaconfig/slurm/value.tt

New versioned schema for slurm 24.05.

ncm-metaconfig: add schema for slurm 24.05

---

ncm-network/src/main/perl/network.pm
ncm-network/src/main/perl/nmstate.pm
ncm-network/src/test/perl/nmstate_advance.t

ncm-network: nmstate: simple interfaces reorder on apply/delete

---

ncm-ssh/src/main/pan/components/ssh/schema.pan

ncm-ssh: add ssh/sshd option GSSAPIKexAlgorithms to schema

---

ncm-freeipa/src/main/perl/freeipa.pm
ncm-freeipa/src/test/perl/aii-basic.t
ncm-opennebula/src/main/perl/OpenNebula/AII.pm
ncm-opennebula/src/test/perl/aii_kickstart.t

Requires https://github.com/quattor/aii/pull/347

/var/tmp is supposed to be reboot persistent 

---

ncm-opennebula/src/main/resources/raw_level1.tt
ncm-opennebula/src/main/resources/tests/regexps/aii_vmtemplate/vm_template
ncm-opennebula/src/test/perl/rpcdata.pm

ncm-opennebula: do not use qxl video driver

---

ncm-network/src/main/pan/components/network/types/network/backend/nmstate.pan
ncm-network/src/test/resources/nmstate_advance.pan

ncm-network: nmstate: Fix indentation errors

---

ncm-metaconfig/src/main/metaconfig/conntrackd/pan/schema.pan
ncm-network/src/main/perl/nmstate.pm
ncm-sudo/src/main/pan/components/sudo/schema.pan

Various fixes for issues that are currently preventing the documentation from building by upsetting `pod2rst` and `sphinx`.

Documentation fixes
